var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var d=0;return function(){return d<c.length?{done:!1,value:c[d++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,f){c!=Array.prototype&&c!=Object.prototype&&(c[d]=f.value)};$jscomp.getGlobal=function(c){c=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,c];for(var d=0;d<c.length;++d){var f=c[d];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(c,d){this.$jscomp$symbol$id_=c;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:d})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function c(f){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+d++,f)}var d=0;return c}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.asyncIterator;c||(c=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};
$jscomp.iteratorFromArray=function(c,d){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var f=0,g={next:function(){if(f<c.length){var m=f++;return{value:d(m,c[m]),done:!1}}g.next=function(){return{done:!0,value:void 0}};return g.next()}};g[Symbol.iterator]=function(){return g};return g};
$jscomp.polyfill=function(c,d,f,g){if(d){f=$jscomp.global;c=c.split(".");for(g=0;g<c.length-1;g++){var m=c[g];m in f||(f[m]={});f=f[m]}c=c[c.length-1];g=f[c];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(f,c,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.values",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(c,f){return f})}},"es8","es3");"undefined"==typeof GamePageHandler&&(GamePageHandler={});
(function(){function c(){var b=$("#category_filter_collapse_container").is(":visible")?$('#category_filter_collapse_container,#category_filter_container div[id!="group-'+PageConfig.defaultCategoryGroup+'"]'):$("#category_filter_container div");b=JSON.parse(p(b));return 1===b.length&&0<=PageConfig.appCategoryId.indexOf(b[0])}let d=function(b){$(document).off("click","#gamePage_container li span.favorite");$(document).on("click","#gamePage_container li span.favorite",function(a){a=$(this);a.toggleClass("active");
t(a.data("pk"))});g(1,b)};var f=function(b){u(b);$(document).on("click","#category_filter_container div ul li input:checkbox, #category_filter_collapse_container ul li input:checkbox",function(a){g(1,b)});$(document).on("click","#category_filter_container div ul li input:radio, #category_filter_collapse_container ul li input:radio",function(a){var k=$(a.currentTarget);k.attr("checked")?(k.attr("checked",!1),k.prop("checked",!1)):($("[name="+a.currentTarget.name+"]").attr("checked",!1),k.attr("checked",
!0),k.prop("checked",!0));g(1,b)});$("#filter_clear_btn").click(function(a){$("#category_filter_container div ul li input").prop("checked",!1);g(1,b)});$(".btn-select-more").click(function(a){var b="open"===$(this).data("select-more")?[$("#category_filter_collapse_container"),$("#category_filter_container div:first")]:[$("#category_filter_container div:first"),$("#category_filter_collapse_container")];a=p(b[0]);var h=r(b[0]);if(0<JSON.parse(a).length){a=JSON.parse(a)[0];var e="checkbox"}else if(0<
h.toString().length)a=h,e="radio";else return;b[1].find("ul li input:"+e).prop("checked",!1);0<a.toString().indexOf(",")?a.split(",").forEach(function(a){b[1].find("ul li input:"+e+"[data-category='"+parseInt(a)+"']").prop("checked",!0)}):b[1].find("ul li input:"+e+"[data-category='"+parseInt(a)+"']").prop("checked",!0)})},g=function(b,a,c){$("#slot_games_paging").size()&&$("#slot_games_paging").bootpag({page:b});c||q.boot({page:b});var h=$("#category_filter_collapse_container").is(":visible")?$('#category_filter_collapse_container,#category_filter_container div[id!="group-'+
PageConfig.defaultCategoryGroup+'"]'):$("#category_filter_container div"),e=p(h);h=r(h);var k="displayOrder",l=$("#game-sort-wrap");l&&(l=l.find("li .active"),0<l.size()&&(k=$(l.get(0)).data("sort")));l=$("#gameSearch").val();null!=l&&""!==l?v(l,e,h,k,a,b):w(e,h,k,b,a,c)},m=function(b){$("#game-sort-wrap li .btn-sort").click(function(a){a.preventDefault(a);a=$(a.currentTarget);a.hasClass("active")||($("#game-sort-wrap").find("li .btn-sort").removeClass("active"),a.addClass("active"),g(1,b))})},x=
function(b){$("#slot_games_paging").bootpag({page:1,total:1,maxVisible:10}).on("page",function(a,c){$(this).data("page",c);g(c,b)}).data("total-pages",1)},B=function(b){y(function(a){z(b,a);$("#gamePage_promotion_container").slick({speed:1E3,infinite:!0,pauseOnHover:!0,pauseOnDotsHover:!0,dots:!0,arrows:!1,autoplay:!0,autoplaySpeed:3E3});A();(a=$("#gamePage_promotion_container"))&&DataImageUtils.setBackground(a)},b)},y=function(b,a){var c="";c=a===GameType.SLOT?"/guest/getSlotPromotionMessages?rnd=":
a===GameType.ARCADE?"/guest/getArcadePromotionMessages?rnd=":a===GameType.FH?"/guest/getFishPromotionMessages?rnd=":a===GameType.CASINO?"/guest/getCasinoPromotionMessages?rnd=":a===GameType.LOTTERY?"/guest/getLotteryPromotionMessages?rnd=":"/guest/getTablePromotionMessages?rnd=";PageConfig.isLogin&&(c=a===GameType.SLOT?"/player/getSlotPromotionMessages?rnd=":a===GameType.ARCADE?"/player/getArcadePromotionMessages?rnd=":a===GameType.FH?"/player/getFishPromotionMessages?rnd=":a===GameType.CASINO?"/player/getCasinoPromotionMessages?rnd=":
a===GameType.LOTTERY?"/player/getLotteryPromotionMessages?rnd=":"/player/getTablePromotionMessages?rnd=");$.ajax({url:c+Math.random(),type:"GET",dataType:"json",data:{}}).done(function(a){200==a.status?b(a.data):Trace.error(a)}).fail(function(a){Trace.error(a);DialogHandler.showErrorAlert()})},z=function(b,a){$.each(a,function(a,b){b.id="message-"+b.pk});TemplateUtil.autoBindListData(a,"#gamePage_promotion_template","#gamePage_promotion_container")},A=function(){$("#gamePage_promotion_container li a").click(function(b){b=
$(b.currentTarget).data("pk");var a="/guest/getPromotionMessageDetail?rnd=";PageConfig.isLogin&&(a="/player/getPromotionMessageDetail?rnd=");$.ajax({url:a+Math.random(),type:"GET",dataType:"json",data:{id:b}}).done(function(a){a.contentType==MessageContentType.TEXT.value?DialogHandler.showMessageDetail(a):a.contentType==MessageContentType.LINK.value&&UiHandler.handleOpenUrl(a)}).fail(function(a){Trace.error(a);DialogHandler.showErrorAlert()})})},p=function(b){var a=[];$.each(b,function(b,c){var e=
"";b=$(c).find("ul li input:checkbox:checked");$.each(b,function(a,b){e=""==e?$(b).data("category"):e+(","+$(b).data("category"))});""!=e&&a.push(e)});return JSON.stringify(a)},r=function(b){var a="";$.each(b,function(b,c){var e="";b=$(c).find("ul li input:radio:checked");$.each(b,function(a,b){""==e&&(e=$(b).data("category"))});""!=e&&(a=""==a?e:a+(","+e))});return a},w=function(b,a,c,h,e,d){$.ajax({url:(PageConfig.isLogin?"/player/getGamesWithCategory":"/guest/getGamesWithCategory")+"?v="+Math.random(),
type:"POST",dataType:"json",data:{checkboxGameCategory:b,gameCategory:a,sort:c,page:h,gameType:e.value}}).done(function(a){200==a.status?GamePageHandler.renderGames(a,d):Trace.error(a)}).fail(function(a){Trace.error(a);DialogHandler.showErrorAlert()})},v=function(b,a,c,h,e,d){$.ajax({url:(PageConfig.isLogin?"/player/searchGames":"/guest/searchGames")+"?v="+Math.random(),type:"POST",dataType:"json",data:{gameName:b,checkboxGameCategory:a,gameCategory:c,sort:h,page:d,gameType:e.value}}).done(function(a){200==
a.status?GamePageHandler.renderGames(a):Trace.error(a)}).fail(function(a){Trace.error(a);DialogHandler.showErrorAlert()})};GamePageHandler.renderGames=function(b,a){var d=b.data;d&&0!=d.length?($("#noGame").size()&&$("#noGame").hide(),$("#noGameApp").size()&&$("#noGameApp").hide()):($("#gamePage_container").empty(),$("#noGame").size()&&$("#noGame").hide(),$("#noGameApp").size()&&$("#noGameApp").hide(),"bv"===PageConfig.webSiteType&&c()||"ip"===PageConfig.webSiteType?$("#noGameApp").size()&&$("#noGameApp").show():
$("#noGame").size()&&$("#noGame").show());PageConfig.isLogin&&(n=b.favoriteList);$("#slot_games_paging").size()?1<b.totalPages?$("#slot_games_paging").bootpag({total:b.totalPages}).show():$("#slot_games_paging").hide():1<=b.totalPages&&q.boot({total:b.totalPages});$.each(d,function(a,b){b.pk=b.id;b.id="game-"+b.id});b=$("#gamePage_container").parent();if(b.hasClass("left")||b.hasClass("right"))d=d.slice(0,4);b={};a&&(b.append=a);TemplateUtil.autoBindListData(d,"#gamePage_template","#gamePage_container",
b);$.each(d,function(a,b){a=$("#"+b.id);b.tag&&a.find("div.tag").addClass(b.tagClass);a.find("img").attr("alt",b.gameName)});a=$("#gamePage_container").find("li div div .trialPlayBtn");$.each(a,function(a,b){a=$(b);let c=a.data("type");b=GameType.values().find(a=>a.getShortName()===c);if((a.data("trialplaytype")&b.value)!=b.value)a.hide();else{b=a.data("vendor");var e=a.data("type"),d=a.data("code");GameType.LOTTERY.getShortName()===e&&"Saba"===b?a.attr("data-href","/guest/viewGame?t="+GameType.Sport.getShortName()+
"&v="+b+"&act="+d):a.attr("data-href","/guest/viewGame?t="+e+"&v="+b+"&g="+d)}});PageConfig.isLogin&&($("#gamePage_container").find("li span.favorite").show(),$.each(n,function(a,b){$("#game-"+b).find("span.favorite").addClass("active")}),a=$("#gamePage_container").find("li div div .playBtn"),$.each(a,function(a,b){a=$(b);b=a.data("vendor");var c=a.data("type"),d=a.data("code");GameType.LOTTERY.getShortName()===c&&"Saba"===b?a.attr("data-href","/player/playGame?t="+GameType.Sport.getShortName()+"&v="+
b+"&act="+d):a.attr("data-href","/player/playGame?t="+c+"&v="+b+"&g="+d)}))};var u=function(b){$.ajax({url:"/guest/getCategoriesByGroup?v="+Math.random(),type:"POST",dataType:"json",data:{gameType:b.value}}).done(function(a){if(200==a.status){a=a.data;$.each(a,function(a,b){"Vendor Group"==b.displayName&&(b.displayName=I18N.get("ui.text.slot.vendor_group"),"ui.text.slot.vendor_group"===b.displayName&&(b.displayName=FE.Translate.get("ui.text.slot.vendor_group")))});TemplateUtil.autoBindListData(a,
"#category_filter_template","#category_filter_container");if("bv"===PageConfig.webSiteType&&(PageConfig.currencyId===CurrencyType.MYR.value||PageConfig.currencyId===CurrencyType.SGD.value)){var c='<button class="slotnewbtn" style="background-image:url(/images/site/slotgame/appButton.png)" onclick=\'window.location.href="/pc/en/app/providerAccount.jsp"\'>918KISS / MEGA888 / PUSSY888</button>';PageConfig.isLogin||(c='<button class="slotnewbtn" style="background-image:url(/images/site/slotgame/appButton.png)" onclick="DialogHandler.showRegister();">918KISS / MEGA888 / PUSSY888</button>');
let a="ma"===PageConfig.lang?"Permainan panas":"Popular Products";$("#category_filter_container").prepend('<div><h4 ui-key="displayName" style="border-style: none;">'+a+"</h4>"+c+"</div>")}$.each($("#category_filter_container div"),function(a,b){$.each($(b).find("ul li"),function(a,b){a=$(b);b=$(a.find("label"));var c=$(b.find("span.game-logo")),d=c.data("vendor");d&&(b.removeClass("btn-gametype"),$("#category_filter_container").data("platform")?(c.addClass("data-image"),c.attr("data-image","/images/web/slotgame/platform/provider-"+
d+".png"),c.attr("style","background-image:url('/images/web/slotgame/platform/provider-"+d+".png');")):c.addClass(d));b=a.attr("id");a.find("input").attr("id","chk-"+b);a.find("label").attr("for","chk-"+b)})});$.each(a,function(a,b){0==b.isCheckbox&&(a=$("#"+b.id),a.find("ul li input").attr("type","radio").attr("name",b.id),a.find("ul li label span.check-cube").removeClass("check-cube").addClass("radio-cube"))})}else Trace.error(a);1===$("#"+PageConfig.defaultCategoryId).size()&&($("#"+PageConfig.defaultCategoryId+
" label").click(),d(b))}).fail(function(a){Trace.error(a);DialogHandler.showErrorAlert()})},n=[],t=function(b){var a="",c=n.indexOf(b);-1!=c?(n.splice(c,1),a="global.text.favorite.removeSuccess"):(n.push(b),a="global.text.favorite.addSuccess");$.ajax({url:"/player/setFavorite",type:"POST",data:{favoriteGames:JSON.stringify(n)}}).done(function(b){200==b.status?DialogHandler.showAlert("global.text.success",a):(Trace.error(b),DialogHandler.showAlert("global.text.notification","global.text.fail"))}).fail(function(a){Trace.error(a);
DialogHandler.showErrorAlert()})},q=function(){var b={page:1,total:1},a;return{init:function(c){window.onscroll=function(){b.page<b.total&&(a||(a=3*$("#gamePage_container").find("li:first")[0].offsetHeight),document.documentElement.scrollTop>document.querySelector(".games-container").offsetHeight-a&&(b.page++,g(b.page,c,!0)))}},boot:function(a){$.extend(b,a)}}}();GamePageHandler.init=function(b){$("#slot_games_paging").size()?x(b):q.init(b);d(b);$("#category_filter_container").size()&&f(b);m(b);setTimeout(function(){B(b)},
1E3);$("#gameSearch").keydown(function(a){KeyEventUtils.isEnterKey(a.which)&&g(1,b)})};GamePageHandler.jackpotFromAPI=function(){function b(){$.ajax({url:"/guest/getJackpotInfo?v="+Math.random(),type:"POST",dataType:"json"}).done(function(a){200===a.status?document.getElementById("jackpotMoney")?document.getElementById("jackpotMoney").innerText=a.jackpot:Trace.error("missing #jackpotMoney"):Trace.error(a)}).fail(function(a){Trace.error(a)})}document.getElementById("jackpotMoney")&&(b(),setInterval(function(){b()},
6E4))};$(".select-wrap-collapse .btn-select-more").click(function(){$(this).parents().find(".top-subnav-wrap").addClass("active")});$(".select-wrap-expand .btn-select-more").click(function(){$(this).parents().find(".top-subnav-wrap").removeClass("active")})})();

