"undefined"==typeof PromotionsPageHandler&&(PromotionsPageHandler={});
(function(){var f=function(){var c="/guest/getMessagesByType?rnd=";PageConfig.isLogin&&(c="/player/getMessagesByType?rnd=");getDataByAjax(c,function(c){AnnouncementHandler.renderAnnouncement(c);AnnouncementHandler.initAnnouncementFlexSlider();AnnouncementHandler.bindAnnouncementOnClick();var b=JsCache.get("#main_announcement_container");b&&(DataImageUtils.setBackground(b),0===c.length?b.css("height","auto"):b.css("height",""))},{messageType:MessageType.PROMOTION_TOP_BANNER.value})},l=function(){var c=
"/guest/getPromotionList?rnd=";PageConfig.isLogin&&(c="/player/getPromotionList?rnd=");getDataByAjax(c,function(c){g(c);h(c);k();window.setTimeout(function(){if(0!=$("#promotion_container .filtr-item").size()){var b="all",a=JsCache.get("#promoFilter").find(".active");null!=a&&(b="m4d"==PageConfig.webSiteType?a.data("filter"):a.parent().data("filter"));a="sameHeight";"tf"==PageConfig.webSiteType&&(a="vertical");JsCache.get("#promotion_container").filterizr({animationDuration:.5,filter:b,layout:a})}},
500)})},g=function(c){c.sort(function(c,b){return c.displayOrder!=b.displayOrder?c.displayOrder-b.displayOrder:b.updateTime-c.updateTime})},h=function(c){var d=[];$.each(c,function(b,a){a.pk=a.id;a.id=a.type==PromotionItemType.NORMAL_DEPOSIT.value||a.type==PromotionItemType.FIRST_DEPOSIT.value?"bonus-"+a.pk:a.type==PromotionItemType.PROMOTION_MESSAGE.value?"bonusmsg-"+a.pk:"bonusother-"+a.pk;a.image=PageConfig.cdnDomain+a.iconPath;a.category=a.gameType;a.type==PromotionItemType.FIRST_DEPOSIT.value&&
(a.category+=", 99");a.category.split(",").forEach(function(a){-1===d.indexOf(parseInt(a))&&d.push(parseInt(a))});a.startDateTime&&(a.startDateTimeStr=DateUtil.format(a.startDateTime,"yyyy/MM/dd HH:mm"));a.endDateTime&&(a.endDateTimeStr=DateUtil.format(a.endDateTime,"yyyy/MM/dd HH:mm"));a.bonusTemplateId&&(a.bonustemplateid=a.bonusTemplateId);a.endDuration=I18N.get("ui.text.promotion.long_term_promo");b=a.endDateTime-(new Date).getTime();if(0>=b)a.endDuration=I18N.get("ui.text.promotion.promo_ended");
else{b=b/1E3/60/60;var c=b/24;if(30>c)if(1>=b)a.endDuration=I18N.get("ui.text.promotion.promo_end_in_1_hr");else if(1>c)a.endDuration=I18N.get("ui.text.promotion.promo_end_in_hr",[parseInt(b)+1]);else{c=parseInt(c);var e=Math.floor(b%24*100)/100;23>Math.floor(b%24*100)/100?e=parseInt(e)+1:(c+=1,e=0);a.endDuration=0<e?I18N.get("ui.text.promotion.promo_end_in_day_hr",[c,e]):I18N.get("ui.text.promotion.promo_end_in_day",[c])}}});0!==d.length&&d.forEach(function(b){$("#promoFilter").find('[data-filter="'+
b+'"]').show()});TemplateUtil.autoBindListData(c,"#promotion_template","#promotion_container");$.each(c,function(b,a){a.type==PromotionItemType.PROMOTION_MESSAGE.value&&a.displayActiveRange&&(b=$("#"+a.id),b.find("p.time").css("opacity","0"),b.find("div.explanation-wrap a.deposit").css("opacity","0").css("cursor","auto").attr("onclick",""));a.bonusCategoryType==BonusCategoryType.REALTIME_REBATE.value&&PageConfig.isLogin&&(b=$("#"+a.id+" > div > div > a.deposit"),b.length&&(b.removeClass("deposit"),
b.addClass("button_apply_pv"),b.text(I18N.get("ui.text.selfhelp.apply")),b.removeAttr("onclick"),b.unbind("click")));a.awardingType!==BonusAwardingType.DEPOSIT.value&&(b=document.getElementById(`${a.id}`))&&b.querySelector(".btn-default-xs.deposit")&&(b.querySelector(".btn-default-xs.deposit").style.display="none");a.displayActiveRange||(b=document.getElementById(`${a.id}`),null!==a.activeRangeContent&&(b.querySelector(".time").textContent=a.activeRangeContent));(b=$("#"+a.id+" .promosi-img"))&&b.css("background-image",
"url("+PageConfig.cdnDomain+a.iconPath+")")})},k=function(){$("#promotion_container li div.explanation-wrap a.detail").click(function(c){var d=$(c.currentTarget).data("pk");$(c.currentTarget).data("type");c="/guest/getPromotionMessageDetail?rnd=";PageConfig.isLogin&&(c="/player/getPromotionMessageDetail?rnd=");$.ajax({url:c+Math.random(),type:"GET",dataType:"json",data:{id:d}}).done(function(b){b.contentType==MessageContentType.TEXT.value?DialogHandler.showMessageDetail(b):b.contentType==MessageContentType.LINK.value&&
UiHandler.handleOpenUrl(b)}).fail(function(b){Trace.error(b);DialogHandler.showErrorAlert()})})};PromotionsPageHandler.init=function(){$("#promoFilter li").click(function(){"m4d"==PageConfig.webSiteType?($("#promoFilter li").removeClass("active"),$(this).addClass("active")):($("#promoFilter li").find("a").removeClass("active"),$(this).find("a").addClass("active"))});$("#promoFilter li").first().click();setTimeout(function(){f()},1E3);l();$(document).on("click",".button_apply_pv",function(){var c=
$(this).attr("data-bonustemplateid");JsCache.get("#pvApplyButton").data("templateid",c);PromotionsPageHandler.previewPromotionVerification(c)});$("#pvApplyButton").click(function(){JsCache.get("#pvApplyButton").attr("disabled",!0);var c=JsCache.get("#pvApplyButton").data("templateid");PromotionsPageHandler.applyPromotionVerification(c)})}})();"undefined"==typeof PromotionHandler&&(PromotionHandler={});
(function(){PromotionHandler.bindReloadAftCloseDialog=function(){JsCache.get("#custAlertOuter .btn-close").on("mousedown",function(){window.location.href="/page/player/promotions.jsp"})}})();

