var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(b,a){var d=this;d instanceof String&&(d=String(d));var c=d.length;a=a||0;for(0>a&&(a=Math.max(a+c,0));a<c;a++){var e=d[a];if(e===b||Object.is(e,b))return!0}return!1}},"es7","es3");
"undefined"==typeof OnlineSeviceHandler&&(OnlineSeviceHandler={});
(function(){OnlineSeviceHandler.initHeaderCs=function(){$.each(PageConfig.csList,function(a,b){b.id=""+b.id;-1===b.id.indexOf("-")?b.id="cs-header-"+b.id:b.id=b.id.replace("-","-header-");b.displayText=b.value});TemplateUtil.autoBindListData(PageConfig.csList,"#header_cs_template","#header_cs_container");"bj"===PageConfig.webSiteType&&$("#header_cs_container").append("<li>\n\t\t\t\t\t<a onclick=\"window.open('/guest/forumLogin', '_blank', 'width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no')\" class=\"icon-forum\">Forum</a>\n\t\t\t\t</li>");$.each(PageConfig.csList,
function(a,b){a=$("#"+b.id);let c=CustomerServiceType.getInstanceOf(b.customerServiceType),d="";c&&(d=c.headerCsClass);b.link&&(c===CustomerServiceType.EMAIL?a.html('<a href="mailto:'+b.link+'" target="_blank">'+b.value+"</a>"):c===CustomerServiceType.Phone?a.html('<a href="tel:'+b.link+'" target="_blank">'+b.value+"</a>"):a.find("a").click(function(){window.open(b.link,"_blank","width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no")}));a.find("a").addClass(d)});
"se"===PageConfig.webSiteType&&$("#header_cs_container").append("<li>\n\t\t\t\t\t<a onclick=\"window.open('https://b.link/zjh28d', '_blank', 'width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no')\" class=\"icon-whatsapp\">WhatsApp</a>\n\t\t\t\t</li>");PageConfig.liveChat&&PageConfig.liveChat[PageConfig.webSiteType]["freshbot.client"]&&($("#header_cs_container .icon-phone").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href"),$("#header_cs_container .icon-phone").click(function(a){$("#mobile-chat-container").click()}));
PageConfig.liveChat&&PageConfig.liveChat[PageConfig.webSiteType]["intercom.app_id"]&&($("#header_cs_container .icon-cs").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href"),$("#header_cs_container .icon-cs").addClass("intercom_custom_launcher"))};OnlineSeviceHandler.initFloatingCs=function(){$.each(PageConfig.csList,function(a,b){b.id=""+b.id;-1==b.id.indexOf("-")?b.id="cs-"+b.id:b.id=b.id.replace("header-","");b.displayText=b.value});TemplateUtil.autoBindListData(PageConfig.csList,
"#side_cs_template","#side-cs-cont");$.each(PageConfig.csList,function(a,b){a=$("#"+b.id);let c=CustomerServiceType.getInstanceOf(b.customerServiceType),d="";c&&(d=c.headerCsClass);b.link?c===CustomerServiceType.EMAIL?a.find("span[ui-key='displayText']").parent().attr("href","mailto:"+b.link):c===CustomerServiceType.SKYPE?a.find("span[ui-key='displayText']").parent().attr("href","skype:"+b.link):a.click(function(){window.open(b.link,"_blank","width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no")}):
a.css("cursor","auto");b.qrCodePath||(a.find(".qr-code").remove(),a.find(".contact-service-qrcode").remove());a.find('img[ui-key="iconPath"]').attr("alt",b.name);a.addClass(d)});PageConfig.liveChat&&PageConfig.liveChat[PageConfig.webSiteType]["freshbot.client"]&&($("#side-cs-cont .icon-phone").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href"),$("#side-cs-cont .icon-phone a").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href"),$("#side-cs-cont .icon-phone").click(function(a){$("#mobile-chat-container").click()}));
PageConfig.liveChat&&PageConfig.liveChat[PageConfig.webSiteType]["intercom.app_id"]&&($("#side-cs-cont .icon-cs").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href"),$("#side-cs-cont .icon-cs a").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href"),$("#side-cs-cont .icon-cs").addClass("intercom_custom_launcher"))};OnlineSeviceHandler.initClickCsLink=function(){var a="";$.each(PageConfig.csList,function(b,c){CustomerServiceType.getInstanceOf(c.customerServiceType)===
CustomerServiceType.CSLINK&&(a=c.link)});PageConfig.liveChat&&PageConfig.liveChat[PageConfig.webSiteType]["freshbot.client"]&&$(".click_cs_link").unbind("click").removeAttr("onclick").removeAttr("target").removeAttr("href");PageConfig.liveChat&&PageConfig.liveChat[PageConfig.webSiteType]["intercom.app_id"]&&$(".click_cs_link").removeClass("click_cs_link").addClass("intercom_custom_launcher");$(".click_cs_link").click(function(b){"se"===PageConfig.webSiteType?window.fcWidget.open():PageConfig.liveChat&&
PageConfig.liveChat[PageConfig.webSiteType]["freshbot.client"]?$("#mobile-chat-container").click():window.open(a,"_blank","width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no")})}})();let showLangUI=!1;
$(document).ready(function(){changeLangSelect(PageConfig.currencyName,PageConfig.lang);initHeaderInnerTime();$("#lang-ul li").click(function(a){a=a.currentTarget;let b=$(a).data("val"),c=$(a).data("currency");changeLangSelect(c,b);null!=c?setTimeout(function(){changeCurrencyLang(CurrencyType[c].value,b)},300):setTimeout(changeLanguage,300)});JsCache.get("#lang-ul")&&($("#language_wrap, #lang_select").mouseover(function(){showLangUI=!0}),$("#language_wrap").mouseout(function(){showLangUI=!1}),$("#lang-ul").mouseover(function(){showLangUI=
!0}),setInterval(function(){showLangUI?JsCache.get("#lang-ul").show():JsCache.get("#lang-ul").hide()},300));$("#language_wrap.language-wrap-pop").click(function(a){DialogHandler.showCurrencyLangPopup()});$("#currency_lang_popup .language-list label").click(function(a){a=$(a.currentTarget);changeCurrencyLang(a.data("currency"),a.data("lang"))});$("#themeToggleBtn").click(function(){var a=$(".toggle-theme-wrap"),b=a.hasClass("dark")?".light-icon":".dark-icon";a=a.find(b).data("theme");b=new Date;b.setTime(b.getTime()+
2592E6);document.cookie="siteTheme="+a+";expires="+b.toUTCString()+";path=/";location.reload()})});var changeLangSelect=function(a,b){document.body.lang=b;if(JsCache.get("#lang_select")){var c=JsCache.get("#lang_select");c.data("val",b);"bv"===PageConfig.webSiteType?c.html("<span>"+a+" - "+I18N.get("ui.text.lang."+b)+'</span><div class="lang-flag '+b+'" style="background-image: url(/images/web/flag-sprite.png);"></div>'):(a=`
				<img src="/images/web/flag/${a.toLowerCase()}.png" alt="${b}">
				<p>
					<span>${PageConfig.currencySymbol}&nbsp;${a}</span>&nbsp;${I18N.get("ui.text.lang."+b)}
				</p>
			`,c.html(a))}},changeLanguage=function(){var a=JsCache.get("#lang_select").data("val");$.ajax({url:"/guest/changeLanguage?"+Math.random(),type:"POST",dataType:"json",data:{lang:a}}).done(function(b){if(200==b.status){let b=top.location.href,d=top.location.href.replace("/"+PageConfig.lang+"/","/"+a+"/");top.location.href=d;setTimeout(function(){b===d&&top.location.reload()},500)}}).fail(function(b){Trace.error(b)}).always(function(){})},changeCurrencyLang=function(a,b){$.ajax({url:"/guest/changeCurrencyLang?"+
Math.random(),type:"POST",dataType:"json",data:{currencyId:a,lang:b}}).done(function(a){if("200"===a.status){var d=a.data;a=d?d.country:"";const c=d?d.redirectToNewWeb:"";if(a){d=d.redirectTo;let e=window.location.pathname;const f=e.substring(1).split("/");if(0<f.length){const h=!!CountryType.getByName(f[0]);let g=e.includes(`/${PageConfig.lang}/`);if("/"===e||c)e="";c||(g&&(1<f.reduce((a,b)=>b===PageConfig.lang?a+1:a,0)?(e=e.replace(`/${PageConfig.lang}/`,"/"),g=!1):e=e.replace(`/${PageConfig.lang}/`,
`/${b}/`)),e=h?e.replace(`/${f[0]}/`,g?`/${a}/`:`/${a}/${b}/`):`/${a}${g?"":`/${b}/`}${e}`);top.location.href=`${d?`${d}`:""}${e}`}}else top.location.href=top.location.href.replace("/"+PageConfig.lang+"/","/"+b+"/")}}).fail(function(a){Trace.error(a)}).always(function(){})},initHeaderInnerTime=function(){var a=8,b=function(a,b){a="000000000"+a;return a.substr(a.length-b)},c=function(a){return 0>=a?"+"+b(-1*a,2):"-"+b(a,2)};setInterval(function(){var d=new Date,f=d.getTime(),e=d.getTimezoneOffset()/
60;f+=36E5*e;a!==e&&(a=-1*e);void 0!=a&&(d=new Date(f+36E5*a),e=-1*a);JsCache.get("#header_inner_time")&&(JsCache.get("#header_inner_time").html("(GMT"+c(e)+":00) "+b(d.getHours(),2)+":"+b(d.getMinutes(),2)+":"+b(d.getSeconds(),2)),JsCache.get("#header_inner_time").attr("title",d.getFullYear()+"/"+b(d.getMonth()+1,2)+"/"+b(d.getDate(),2)))},1E3)};

