"undefined"==typeof LoginHandler&&(LoginHandler={});
(function(){function e(){$(".tab-primary-box").each(function(a){var b=$(this).find("ul>li").width();$(this).parents(".content").find(".main-tab-content").children(".tab-pane").eq(0).addClass("active");$(this).find(".slider-tab").css("width",b);$(this).find("ul>li").click(function(a){a=$(this).index();var d=a*b;$(this).parent().siblings(".slider-tab").stop(!0,!1).animate({left:d},100);$(".main-tab-content").find(".tab-pane").eq(a).addClass("active").siblings().removeClass("active");$(this).parents(".content").find(".main-tab-content").children(".tab-pane").eq(a).addClass("active").siblings().removeClass("active")})})}
var f=function(){var a=$("#loginForm");PageConfig.loginValidator=a.validate({onfocusout:!1,onkeyup:!1,errorPlacement:function(b,c){var d="";""==c.val()&&(d=" "+c.attr("placeholder"));c.parent().addClass("wrong");a.find("div.error").addClass("active").html('<i class="icon-error"></i><span>'+b.text()+d+"</span>")},errorClass:"wrong"});a.find("#loginUsername").rules("add",{required:!0,maxlength:15,userId:!0});a.find("#loginPassword").rules("add",{required:!0,maxlength:20,playerLoginPassword:!0})},g=
function(a){a.preventDefault(a);JsCache.get("#loginPopup")&&(JsCache.get("#pop_bg_login").fadeIn(),JsCache.get("#loginPopup").fadeIn());if(JsCache.get("#loginPopup").hasClass("login-pop-group")){if("matrix(1, 0, 0, 1, -400, 0)"===JsCache.get("#loginPopup").find("div.pop-inner div.input-slides").css("transform")){let a=$(".input-forget").outerHeight();setTimeout(()=>{$(".login-pop-group .input-slides").css("height",a)},300)}else a=$("#loginPopup").find(".input-login").outerHeight(),$(".input-slides").css("height",
a);e();appendAllCallingCodeList()}},h=function(a){a.preventDefault(a);JsCache.get("#loginPopup").fadeOut();JsCache.get("#pop_bg_login").fadeOut();JsCache.get("#loginPopup").hasClass("login-pop-group")&&(JsCache.get("#loginPopup").addClass("hide"),setTimeout(function(){JsCache.get("#loginPopup").removeClass("hide").removeClass("active");JsCache.get("#loginPopup").find(".tips-warning").removeClass("active")},1E3),$(".login-pop-group .fail-pop").addClass("hide"),setTimeout(function(){$(".login-pop-group .fail-pop").removeClass("hide").removeClass("active")},
500))},k=function(a){a.preventDefault(a);$("#loginButton").prop("disabled",!0);a=JsCache.get("#loginUsername");a.val(a.val().toLowerCase());if(a.valid()){a.parent().removeClass("wrong");var b=JsCache.get("#loginPassword");if(b.valid()){b.parent().removeClass("wrong");JsCache.get("#loginForm").find("div.error").removeClass("active");var c=a.val();a=b.val();LoginHandlerUtil.guestLogin(c,a,null,function(a){200!=a.status?(PageConfig.isInHouse?DialogHandler.showLoginError(a.message,a.loginFailTimes,a.accountLock,
a.forgetPasswordUnlockAccount):DialogHandler.showAlert("global.text.fail",a.message),$("#loginButton").prop("disabled",!1)):(PageConfig.tracking&&PageConfig.tracking[PageConfig.webSiteType]&&PageConfig.tracking[PageConfig.webSiteType].sportRadarId&&SportradarHandler.loginSuccess(c),setTimeout(()=>{window.location.replace("/")},500))})}else $("#loginButton").prop("disabled",!1)}else $("#loginButton").prop("disabled",!1)},l=function(){$(".login-pop-group").find(".input-forget").find(".tab-pane").eq(0).addClass("active");
let a=$("#loginPopup").hasClass("login-pop-group");$("#link_forget").click(()=>{JsCache.get("#loginPopup").find("div.pop-inner div.input-slides").css("transform","translateX(-400px)");a&&setTimeout(()=>{$(".login-pop-group .input-slides").css("height",$(".input-forget").outerHeight())},300)});$("#link_login").click(()=>{a?(setTimeout(()=>{JsCache.get("#loginPopup").find("div.pop-inner div.input-slides").css("transform","translate3d(0px, 0px, 0px)")},300),$(".input-slides").css("height",$("#loginPopup").find(".input-login").outerHeight())):
JsCache.get("#loginPopup").find("div.pop-inner div.input-slides").css("transform","translate3d(0px, 0px, 0px)")})};LoginHandler.init=function(){f();l();$("#header-login").on("click",g);$("#loginPopup .btn-close").on("click",h);$("#loginButton").on("click",k);$("#loginPassword").keydown(function(a){KeyEventUtils.isEnterKey(a.which)&&($("#loginPassword").unbind("keydown"),$("#loginButton").trigger("click"))});$("#loginUsername").blur(function(){var a=$(this);a.val($.trim(a.val()))})}})();

