"undefined"==typeof RegisterPageHandler&&(RegisterPageHandler={});
(function(){var k=function(){var a=$("#registerForm");PageConfig.registerValidator=a.validate({errorPlacement:function(a,b){b.parent().hasClass("input-group")||"ageCheck"==b.attr("id")||b.parent().hasClass("phone-info")?a.insertAfter(b.parent()):a.insertAfter(b)},errorElement:"span",errorClass:"error",highlight:function(a){$(a).closest("td").addClass("has-error");$(a).closest("fieldset").addClass("has-error")},unhighlight:function(a){$(a).closest("td").removeClass("has-error");$(a).closest("fieldset").removeClass("has-error")},
ignore:[]});a.find("[name='username']").rules("add",{required:!0,maxlength:15,userId:!0,messages:{required:I18N.get("msg.error.account.isNotValidated")}});a.find("[name='password']").rules("add",{required:!0,playerRegisterPassword:!0,playerPasswordEqualToAccount:"[name='username']",messages:{required:I18N.get("msg.error.password.player.isNotValidated")}});a.find("[name='confirmPassword']").rules("add",{required:!0,equalTo:"#password",messages:{required:I18N.get("msg.error.password.player.isNotValidated"),
equalTo:I18N.get("msg.error.confirmPassword.incorrect")}});"tf"===PageConfig.webSiteType&&a.find("[name='birthDatePicker']").rules("add",{required:!0,minlength:10,maxlength:10,date2:!0,checkAgeOver18:!0});a.find("[name='ageCheck']").rules("add",{required:!0});a.find("[name='realName']").rules("add",{required:!0,alphanumeric2WithSpace:"se"===PageConfig.webSiteType});a.find("[name='phoneNumber']").rules("add",{required:!0,byCallingCode:function(){return[$("[name=callingCode]").val()]},messages:{byCallingCode:function(){return I18N.get("msg.error.account.phone.isNotValidated")}}});
a.find("[name='email']").rules("add",{required:function(){let a=parseInt($("#currencyType").val());return!("bv"===PageConfig.webSiteType&&a===CurrencyType.MYR.value)},maxlength:50,email:!0});a.find("[name='qqId']").rules("add",{qqId:!0});a.find("[name='wechatId']").rules("add",{weChatId:!0});a.find("#captchaInput").rules("add",{required:!0,messages:{required:I18N.get("msg.error.validation.captcha")}});a.find("[name=userBankId]").rules("add",{required:!0,messages:{required:I18N.get("msg.error.validation.bankNameIsNotValid")}});
a.find("[name=userBankNo]").rules("add",{required:!0,cnBankAccNumber:!0})},d=function(){var a=0,c=JsCache.get("#registerForm");c.find("[name=username]").valid()||a++;c.find("[name=password]").valid()||a++;c.find("[name=confirmPassword]").valid()||a++;return 0==a},e=function(a){a=0;var c=JsCache.get("#registerForm");c.find("[name=realName]").valid()||a++;c.find("[name=phoneNumber]").valid()||a++;"pb"===PageConfig.webSiteType||"c7"===PageConfig.webSiteType||"ab"===PageConfig.webSiteType||c.find("[name=email]").valid()||
a++;hasStep3||c.find("#captchaInput").valid()||a++;!hasStep3&&0<JsCache.get("#ageCheck").size()&&!c.find("[name=ageCheck]").valid()&&a++;return 0===a},f=function(a){null!=a&&a.preventDefault(a);$("#registerForm").validate().resetForm();$("#step-wrap").removeClass("st2").addClass("st1");$("#step-wrap .step2").removeClass("active");$("#register-form-inner").removeClass("step2");$("#register-form-step1.v2_step1").show();$("#register-form-step2.v2_step2").hide();$("#register-form-step3.v2_step3").hide()},
h=function(a){a.preventDefault(a);d()&&($("#step-wrap").removeClass("st1").addClass("st2"),$("#step-wrap .step2").addClass("active"),$("#register-form-inner").addClass("step2"),$("#register-form-step1.v2_step1").hide(),$("#register-form-step2.v2_step2").show(),$("#register-form-step3.v2_step3").hide())};let l=function(a){a.preventDefault(a);d()&&e()&&($("#userBankAccount").val($("#realName").val()),$("#step-wrap").removeClass("st2").addClass("st3"),$("#step-wrap .step3").addClass("active"),$("#register-form-inner").addClass("step3"),
$("#register-form-step1.v2_step1").hide(),$("#register-form-step2.v2_step2").hide(),$("#register-form-step3.v2_step3").show())};var g=function(a){a.preventDefault(a);if(!d())f();else if(e()){a=0;var c=JsCache.get("#registerForm");hasStep3&&!c.find("#captchaInput").valid()&&a++;hasStep3&&0<JsCache.get("#ageCheck").size()&&!c.find("[name=ageCheck]").valid()&&a++;if("m4d"===PageConfig.webSiteType||"ip"===PageConfig.webSiteType)c.find("[name=userBankId]").valid()||a++,c.find("[name=userBankNo]").valid()||
a++;0===a&&m()}},m=function(){var a=JsCache.get("#registerButton"),c=a.text();a.prop("disabled",!0);a.text("");a.append('<i class="fa fa-circle-o-notch fa-spin fa-fw"></i>');var b=JsCache.get("#username").val(),x=JsCache.get("#password").val(),d=JsCache.get("#confirmPassword").val(),e=-1;null!=JsCache.get("#currencyType")&&(e=JsCache.get("#currencyType").val());let f="";null!=JsCache.get("#friendReferCode")&&(f=JsCache.get("#friendReferCode").val());var h=JsCache.get("#realName").val(),g="";null!=
JsCache.get("#email")&&(g=JsCache.get("#email").val());var u="";"tf"==PageConfig.webSiteType&&(u=JsCache.get("#birthDatePicker").val());var k=JsCache.get("#callingCode").val(),l=JsCache.get("#phoneNumber").val(),m=JsCache.get("#captchaInput").val(),q=(new TrafficStatistics).get(),r=(new TrafficStatistics({canvas:!0})).get();(new TrafficStatistics({ie_activex:!0})).get();var t=(new TrafficStatistics({screen_resolution:!0})).get(),v="",w="";if("m4d"==PageConfig.webSiteType||"ip"==PageConfig.webSiteType)v=
JsCache.get("#userBankId").val(),w=JsCache.get("#userBankNo").val();var n=new Promise(function(a,b){(new TrafficStatistics2).get(function(b){a(b)})}),p=new Promise(function(a,b){Fingerprint3.load().then(a=>a.get()).then(b=>{b=b.visitorId;console.log(b);a(b)})});"undefined"!==typeof AdElementHandler&&AdElementHandler.update(AdEventType.REGISTER_EVENT,PageConfig.country,PageConfig.lang,{register_id:b});Promise.all([p,n]).then(([n,p])=>{$.ajax({url:"/guest/register",type:"POST",dataType:"JSON",data:{captcha:m,
userId:b,name:h,password:x,currencyType:e,friendReferCode:f,confirmPassword:d,callingCode:k,phone:l,email:g,dateOfBirth:u,userBankId:v,userBankNo:w,fingerprint:q,fingerprint2:p,fingerprintCanvas:r,fingerprintActiveX:n,fingerprintResolution:t},success:function(a){200!=a.status?"Error_ReferCode_Currency"===a.message?(DialogHandler.showAlert("global.text.fail","msg.error.referCode.currency.isNotValidated"),JsCache.get("#custAlertOuter .btn-close").on("mousedown",function(){window.location.href="/?refcode="}),
$("#pop_bg").on("click",function(){window.location.href="/?refcode="})):(DialogHandler.showAlert("global.text.fail",a.message),RegisterPageHandler.getCaptcha()):setTimeout(function(){PageConfig.templateVersion?window.location.href="/#registerSuccess":window.location.replace("/page/player/registerSuccess.jsp")},500)}}).fail(function(a){Trace.error(a)}).always(function(){a.prop("disabled",!1);a.find("i").remove();a.text(c)})})};const t=function(){let a="/guest/getMessagesByType?rnd=";PageConfig.isLogin&&
(a="/player/getMessagesByType?rnd=");getDataByAjax(a,function(a){q(a);$("#register_banner_container").slick({speed:1E3,infinite:!0,pauseOnHover:!0,pauseOnDotsHover:!0,fade:!0,dots:!0,arrows:!1,autoplay:!0,autoplaySpeed:3E3});r();(a=JsCache.get("#register_banner_container"))&&DataImageUtils.setBackground(a)},{messageType:MessageType.REGISTER_SLIDER.value})},q=function(a){$.each(a,function(a,b){b.id="message-"+b.id;b.image=PageConfig.uploadImageUrl+"/upload/registerSlider/"+b.imageSliderPath});TemplateUtil.autoBindListData(a,
"#register_banner_template","#register_banner_container")},r=function(){$("#register_banner_container li a").click(function(a){a=$(a.currentTarget).data("id");let c="/guest/getPromotionMessageDetail?rnd=";PageConfig.isLogin&&(c="/player/getPromotionMessageDetail?rnd=");$.ajax({url:c+Math.random(),type:"GET",dataType:"json",data:{id:a}}).done(function(a){a.contentType==MessageContentType.TEXT.value?DialogHandler.showMessageDetail(a):a.contentType==MessageContentType.LINK.value&&UiHandler.handleOpenUrl(a)}).fail(function(a){Trace.error(a);
DialogHandler.showErrorAlert()})})};RegisterPageHandler.init=function(){"bv"==PageConfig.webSiteType&&$("body").addClass("en");$("#step-wrap .step1").addClass("active").addClass("st1");k();t();$("#username").on("blur",function(a){a=$(a.currentTarget);var b=a.val().toLowerCase();a.val(b)});$("[name='realName']").on("blur",function(a){a=$(a.currentTarget);var b=a.val().replace(/  +/g," ");a.val(b)});RegisterPageHandler.getCaptcha();setInterval(RegisterPageHandler.getCaptcha,6E4);let a=$("#currencyType");
a.on("change",function(b){b=$(b.currentTarget);"bv"==PageConfig.webSiteType&&b.val()==CurrencyType.MYR.value?$("#friendReferCodeRow").show():($("#friendReferCodeRow").hide(),$("#friendReferCode").val(""));b=CountryType.getByCurrency(b.val());console.log("countryType",b);appendCallingCodeListByElem("#registerForm",a.val())});CountryType.getByCurrency(a.val());appendCallingCodeListByElem("#registerForm",a.val());$("#register-form-step1 a.btn-default, #register-form-step1 a.btn-register-next").on("click",
h);$("#register-form-step2 a.btn-register-next").on("click",l);$("#register-form-step2 a#goToStep1").on("click",f);$("#register-form-step2 a#registerButton").on("click",g);$("#register-form-step3 a#goToStep2").on("click",h);$("#register-form-step3 a#registerButton").on("click",g);var c=!1;$("#refresh_captcha,#captcha_image").on("click",function(){c||(c=!0,RegisterPageHandler.getCaptcha())})};RegisterPageHandler.getCaptcha=function(){null!=document.captcha&&(document.captcha.src="/captcha?"+Math.random())}})();

