var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var d=this;d instanceof String&&(d=String(d));var e=d.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var c=d[b];if(c===a||Object.is(c,a))return!0}return!1}},"es7","es3");
"undefined"==typeof websiteCurrencyAndCountryMapping&&(websiteCurrencyAndCountryMapping={});(function(){getWebSiteAllCallingCodes()})();null==websiteCurrencyAndCountryMapping&&getWebSiteAllCallingCodes();function getWebSiteAllCallingCodes(){$.ajax({url:"/guest/getWebSiteAllCallingCodes",type:"GET",dataType:"json",async:!1,data:{}}).success(function(a){"200"==a.status&&(websiteCurrencyAndCountryMapping=a.data)})}function appendCallingCodeList(a){appendCallingCodeListByElem("#add-pop-phone",a)}
function appendCallingCodeListByElem(a,c){let b="",d="";websiteCurrencyAndCountryMapping&&(b=websiteCurrencyAndCountryMapping[c].map(a=>{if(!d.split(",").includes(a.callingCode))return d+=a.callingCode+",",`<option data-country="${a.countryName}" value=${a.callingCode}></option>`}));$(a).find('[name="callingCodeSelect"]').html(b);initCallingCodeList(a)}
function initCallingCodeList(a){let c=[],b="";$(a).find('[name="callingCodeSelect"] > option').each(function(){if(!b.split(",").includes(`${this.value}`)){let a=`/images/web/flag/${$(this).data("country")}.png`;c.push(`<li data-callingcode="${this.value}"><img src="${a}" alt="" /><span>${`+${this.value}`}</span></li>`);b+=`${this.value},`}});$(a).find('[name="callingCodeList"]').html(c);$(a).find(".phone-area-code .btn-select").html(c[0]);$(a).find(".phone-area-code .btn-select").attr("value","en");
$(a).find('[name="callingCode"]').val($(c[0]).data("callingcode"));$(a).find('[name="callingCodeList"] li').unbind("click");$(a).find('[name="callingCodeList"] li').click(function(b){b.preventDefault();var d=$(this).find("img").attr("src");let c=$(this).find("img").attr("value"),e=this.innerText,h=$(this).data("callingcode");d='<li><img src="'+d+'" alt="" /><span>'+e+"</span></li>";$(a).find(".phone-area-code .btn-select").html(d);$(a).find(".phone-area-code .btn-select").attr("value",c);$(a).find('[name="callingCode"]').val(h);
$(a).find('[name="callingCodeGroup"]').toggle();b&&b.stopPropagation&&b.stopPropagation();document.onclick=null});$(a).find('[name="selectCallingCodeBtn"]').unbind("click");$(a).find('[name="selectCallingCodeBtn"]').click(function(b){$(a).find('[name="callingCodeGroup"]').toggle();b&&b.stopPropagation&&b.stopPropagation();document.onclick=function(){$(a).find('[name="callingCodeGroup"]').toggle();$(".select-group").hide();document.onclick=null}});var d=localStorage.getItem("lang");if(d){let b=c.indexOf(d);
$(a).find(".btn-select").html(c[b]);$(a).find(".btn-select").attr("value",d)}else d=c.indexOf("ch"),$(a).find(".btn-select").html(c[d])}
function appendAllCallingCodeList(){let a="",c="";websiteCurrencyAndCountryMapping&&Object.keys(websiteCurrencyAndCountryMapping).forEach(function(b){a+=websiteCurrencyAndCountryMapping[b].map(a=>{if(!c.split(",").includes(a.callingCode))return c+=a.callingCode+",",`<option data-country="${a.countryName}" value=${a.callingCode}></option>`})});$("#callingCodeSelectAll").html(a);initAllCallingCodeList()}
function initAllCallingCodeList(){let a=[],c="";$("#callingCodeSelectAll > option").each(function(){if(!c.split(",").includes(`${this.value}`)){let b=`/images/web/flag/${$(this).data("country")}.png`;a.push(`<li data-callingcode="${this.value}"><img src="${b}" alt="" /><span>${`+${this.value}`}</span></li>`);c+=`${this.value},`}});$(".phone-info .phone-code-list").html(a);$("#selectCallingCodeBtn").html(a[0]);$("#selectCallingCodeBtn").attr("value","en");$("#callingCode").val($(a[0]).data("callingcode"));
$(".phone-info .phone-code-list li").unbind("click");$(".phone-info .phone-code-list li").click(function(a){var b=$(this).find("img").attr("src");let c=$(this).find("img").attr("value"),f=this.innerText,g=$(this).data("callingcode");b='<li><img src="'+b+'" alt="" /><span>'+f+"</span></li>";$("#selectCallingCodeBtn").html(b);$("#selectCallingCodeBtn").attr("value",c);$("#callingCode").val(g);$(".phone-info .phone-code-list-group").toggle();a&&a.stopPropagation&&a.stopPropagation();document.onclick=
null});$("#selectCallingCodeBtn").unbind("click");$("#selectCallingCodeBtn").click(function(a){$("#callingCodeGroup").toggle();a&&a.stopPropagation&&a.stopPropagation();document.onclick=function(){$("#callingCodeGroup").toggle();$(".select-group").hide();document.onclick=null}})}
function appendVerifyCallingCodeList(a,c){let b="",d="";websiteCurrencyAndCountryMapping&&(b=websiteCurrencyAndCountryMapping[a].filter(a=>a.callingCode==c).map(a=>{if(!d.split(",").includes(a.callingCode))return d+=a.callingCode+",",`<option data-country="${a.countryName}" value=${a.callingCode}></option>`}));$('[name="verifyCallingCodeSelect"]').html(b);let e=[];$('[name="verifyCallingCodeSelect"] > option').each(function(){let a=$(this).data("country");e.push(`<li data-callingcode="${this.value}"><img src="${`/images/web/flag/${a}.png`}" alt="" /><span>${`+${this.value}`}</span></li>`)});
$('[name="verifyCallingCodeList"]').html(e);$('[name="verifySelectCallingCodeBtn"]').html(e[0]);$('[name="verifySelectCallingCodeBtn"]').attr("value","en");$('[name="revifyCallingCode"]').val(c)}
function initLoginCallingCodeList(){let a="",c="";websiteCurrencyAndCountryMapping&&Object.keys(websiteCurrencyAndCountryMapping).forEach(function(b){a+=websiteCurrencyAndCountryMapping[b].map(a=>{if(c.split(",").includes(a.callingCode))return"";c+=a.callingCode+",";return`<option data-country="${a.countryName}" value=${a.callingCode}></option>`})});$('[name="callingCodeSelectAll"]').html(a);let b=[];$('[name="callingCodeSelectAll"] > option').each(function(){let a=$(this).data("country");b.push(`<li data-callingcode="${this.value}"><img src="${`/images/web/flag/${a}.png`}" alt="" /><span>${`+${this.value}`}</span></li>`)});
$('[name="callingCodeList"]').html(b);$(".phone-area-code .btn-select").html(b[0]);$('[name="callingCode"]').val($(b[0]).data("callingcode"));$('[name="callingCodeList"] li').unbind("click");$('[name="callingCodeList"] li').click(function(a){a.preventDefault();var b=$(this).find("img").attr("src");let c=$(this).find("img").attr("value"),d=this.innerText,e=$(this).data("callingcode");b='<li><img src="'+b+'" alt="" /><span>'+d+"</span></li>";$(".phone-area-code .btn-select").html(b);$(".phone-area-code .btn-select").attr("value",
c);$('[name="callingCode"]').val(e);$('[name="callingCodeGroup"]').toggle();a&&a.stopPropagation&&a.stopPropagation();document.onclick=null});$('[name="selectCallingCodeBtn"]').unbind("click");$('[name="selectCallingCodeBtn"]').click(function(a){$('[name="callingCodeGroup"]').toggle();a&&a.stopPropagation&&a.stopPropagation();document.onclick=function(){$('[name="callingCodeGroup"]').toggle();$(".select-group").hide();document.onclick=null}});var d=localStorage.getItem("lang");if(d){let a=b.indexOf(d);
$(".btn-select").html(b[a]);$(".btn-select").attr("value",d)}else d=b.indexOf("ch"),$(".btn-select").html(b[d])}
;
