"undefined"===typeof PageConfig&&(PageConfig={});PageConfig.casinoInfo={};PageConfig.casinoInfo.AB={desc1:"ui.text.casinoInfo.AB.desc1",desc2:"ui.text.casinoInfo.AB.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"}]};
PageConfig.casinoInfo.AGIN={desc1:"ui.text.casinoInfo.AG.desc1",desc2:"ui.text.casinoInfo.AG.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemBaccaratSpeed",css:"itemBaccaratSpeed"},{title:"ui.text.casinoInfo.itemPokerBull",css:"itemPokerBull"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"}]};
PageConfig.casinoInfo.BBIN={desc1:"ui.text.casinoInfo.BBIN.desc1",desc2:"ui.text.casinoInfo.BBIN.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemBaccaratSpeed",css:"itemBaccaratSpeed"},{title:"ui.text.casinoInfo.itemPokerBull",css:"itemPokerBull"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemPaiGow",
css:"itemPaiGow"},{title:"ui.text.casinoInfo.itemSedie",css:"itemSedie"},{title:"ui.text.casinoInfo.itemFishPrawnCrab",css:"itemFishPrawnCrab"}]};
PageConfig.casinoInfo.BG={desc1:"ui.text.casinoInfo.BG.desc1",desc2:"ui.text.casinoInfo.BG.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemPokerBull",css:"itemPokerBull"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemGoldenFlower",css:"itemGoldenFlower"}]};
PageConfig.casinoInfo.DG={desc1:"ui.text.casinoInfo.DG.desc1",desc2:"ui.text.casinoInfo.DG.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemPokerBull",css:"itemPokerBull"},{title:"ui.text.casinoInfo.itemGoldenFlower",css:"itemGoldenFlower"}]};
PageConfig.casinoInfo.EVO={desc1:"ui.text.casinoInfo.EVO.desc1",desc2:"ui.text.casinoInfo.EVO.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"}]};
PageConfig.casinoInfo.AWCMEVO={desc1:"ui.text.casinoInfo.EVO.desc1",desc2:"ui.text.casinoInfo.EVO.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"}]};
PageConfig.casinoInfo.HG={desc1:"ui.text.casinoInfo.HG.desc1",desc2:"ui.text.casinoInfo.HG.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"}]};
PageConfig.casinoInfo.MG={desc1:"ui.text.casinoInfo.MG.desc1",desc2:"ui.text.casinoInfo.MG.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"}]};
PageConfig.casinoInfo.SilkStonePT={desc1:"ui.text.casinoInfo.PT.desc1",desc2:"ui.text.casinoInfo.PT.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemHoldem",css:"itemHoldem"},{title:"ui.text.casinoInfo.itemLiveHiLow",
css:"itemLiveHiLow"}]};
PageConfig.casinoInfo.Sunbet={desc1:"ui.text.casinoInfo.Sunbet.desc1",desc2:"ui.text.casinoInfo.Sunbet.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemPokerBull",css:"itemPokerBull"},{title:"ui.text.casinoInfo.itemThreeDucalMinisters",css:"itemThreeDucalMinisters"},
{title:"ui.text.casinoInfo.itemSparrowPaiGow",css:"itemSparrowPaiGow"}]};PageConfig.casinoInfo.SEXYM={desc1:"ui.text.casinoInfo.SEXYM.desc1",desc2:"ui.text.casinoInfo.SEXYM.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"}]};
PageConfig.casinoInfo.SEXY={desc1:"ui.text.casinoInfo.SEXYM.desc1",desc2:"ui.text.casinoInfo.SEXYM.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"}]};
PageConfig.casinoInfo.AWCMSEXY={desc1:"ui.text.casinoInfo.SEXYM.desc1",desc2:"ui.text.casinoInfo.SEXYM.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"}]};
PageConfig.casinoInfo.SA={desc1:"ui.text.casinoInfo.SA.desc1",desc2:"ui.text.casinoInfo.SA.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemMoneyWheel",css:"itemMoneyWheel"},{title:"ui.text.casinoInfo.itemBaccaratBull",css:"itemBaccaratBull"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemFTan",css:"itemFTan"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",
css:"itemSuibao"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"}]};PageConfig.casinoInfo.SBO={desc1:"ui.text.casinoInfo.SBO.desc1",desc2:"ui.text.casinoInfo.SBO.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"}]};PageConfig.casinoInfo.SBOv2=PageConfig.casinoInfo.SBO;
PageConfig.casinoInfo.Preset={desc1:"ui.text.casinoInfo.preset.desc1",desc2:"ui.text.casinoInfo.preset.desc1",playItems:[]};PageConfig.casinoInfo.AWCMSEVENMOJOS={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"}]};
PageConfig.casinoInfo.AWCMVENUS={desc1:"ui.text.casinoInfo.AWCMVENUS.desc1",desc2:"ui.text.casinoInfo.AWCMVENUS.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"}]};
PageConfig.casinoInfo.WM={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemFTan",css:"itemFTan"}]};
PageConfig.casinoInfo.EBET={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemBaccaratSpeed",css:"itemBaccaratSpeed"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemPokerBull",css:"itemPokerBull"}]};
PageConfig.casinoInfo.TCGGPI={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemSedie",css:"itemSedie"}]};
PageConfig.casinoInfo.Ezugi={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemSedie",css:"itemSedie"}]};
PageConfig.casinoInfo.AWCMPT={desc1:"ui.text.casinoInfo.PT.desc1",desc2:"ui.text.casinoInfo.PT.desc2",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemHoldem",css:"itemHoldem"}]};
PageConfig.casinoInfo.AWCMPP={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemBlackJack",css:"itemBlackJack"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"}]};
PageConfig.casinoInfo.RG={desc1:"-",desc2:"-",playItems:[{title:"ui.text.casinoInfo.itemBaccarat",css:"itemBaccarat"},{title:"ui.text.casinoInfo.itemDragonTiger",css:"itemDragonTiger"},{title:"ui.text.casinoInfo.itemRoulette",css:"itemRoulette"},{title:"ui.text.casinoInfo.itemSuibao",css:"itemSuibao"}]};

