"undefined"==typeof FooterHandler&&(FooterHandler={});
(function(){FooterHandler.init=function(){$("#sidebar-pt-dl").click(function(){"undefined"===typeof $(this).attr("href")&&DialogHandler.showAlert("form.text.login","form.text.login.pleaseRegistAlertMessage")});0<$("#beautyVideo").size()&&$("#popupBeautyVideo").is(":visible")&&($("#beautyVideo")[0].play(),$("#muteVideo").click(function(){var a=$("#beautyVideo");a.prop("muted")?(a.prop("muted",!1),$(this).find("img").attr("src",PageConfig.cdnDomain+"/images/site/footer/sound-on.png")):(a.prop("muted",
!0),$(this).find("img").attr("src",PageConfig.cdnDomain+"/images/site/footer/sound-off.png"))}))};FooterHandler.hideVip=function(){$("#popupVip").hide()};FooterHandler.hideBeautyVideo=function(){$("#popupBeautyVideo").fadeOut();$("#beautyVideo")[0].pause()};FooterHandler.showCsPanel=function(){let a=document.getElementById("btn_cc_now");a.style.right="154px"===a.style.right?"0px":"154px";a=document.getElementById("tf-panel-rt");a.style.display="block"===a.style.display?"none":"block";a=$(".cs-panel-right");
1==a.size()&&(9==a.css("z-index")?a.css("z-index",10):a.css("z-index",9))};FooterHandler.initFloatingCs=function(){$.each(PageConfig.csList,function(a,b){b.id=""+b.id;-1==b.id.indexOf("-")?b.id="cs-"+b.id:b.id=b.id.replace("header-","");b.displayText=b.value});TemplateUtil.autoBindListData(PageConfig.csList,"#floating_cs_template","#contact-cont");$.each(PageConfig.csList,function(a,b){a=$("#"+b.id);let c=CustomerServiceType.getInstanceOf(b.customerServiceType);b.link?c===CustomerServiceType.EMAIL?
a.find("p[ui-key='displayText']").html('<a href="mailto:'+b.link+'" target="_blank">'+b.value+"</a>"):c===CustomerServiceType.SKYPE?a.find("p[ui-key='displayText']").html('<a href="skype:'+b.link+'" target="_blank">'+b.value+"</a>"):a.click(function(){window.open(b.link,"_blank","width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no")}):a.css("cursor","auto")})};FooterHandler.initClickCsLink=function(){var a="";$.each(PageConfig.csList,function(b,c){CustomerServiceType.getInstanceOf(c.customerServiceType)===
CustomerServiceType.CSLINK&&(a=c.link)});$(".click_cs_link").click(function(b){window.open(a,"_blank","width=750,height=750,toolbar=no,scrollbars=no,menubar=no,status=no,resizable=yes,location=no")})};FooterHandler.adjustCustomerService=function(){$.each(PageConfig.csList,function(a,b){a=$("#"+b.id);let c=CustomerServiceType.getInstanceOf(b.customerServiceType);a.find(".link").hide();a.find(".wechat").hide();null!=b.qrCodePath?(a.find(".wechat").show(),a.find("span[ui-key='displayText']").html(b.value+
'<img src="'+b.iconPath+'">')):a.find(".link").show();c===CustomerServiceType.EMAIL?a.find(".link").attr("href","mailto:"+(b.link?b.link:b.value)).attr("target","_blank"):c===CustomerServiceType.SKYPE&&a.find(".link").attr("href","skype:"+(b.link?b.link:b.value)).attr("target","_blank")})}})();"undefined"==typeof MsgDetailPopupHandler&&(MsgDetailPopupHandler={});
(function(){MsgDetailPopupHandler.popupUpdatePasswordForm=function(a,b){a?(JsCache.get("#resetCurrentPassword").parents("tr").hide(),JsCache.get("#resetPasswordButton").data("p",b)):JsCache.get("#resetCurrentPassword").parents("tr").show();JsCache.get("#resetPasswordButton").data("isClient",a);$("#pop_bg").fadeIn();JsCache.get("#reset_password_popup").show().animate({opacity:1},200,function(){JsCache.get("#reset_password_popup .cust-alert").animate({"margin-top":"120px"},100)})};MsgDetailPopupHandler.closeMsg=
function(a){var b=$(a).parent();b.find(".cust-alert").animate({"margin-top":"-100%",top:0},300,function(){b.animate({opacity:0},200,function(){b.hide()})});$("#pop_bg").fadeOut()}})();"undefined"==typeof QuickTransferHandler&&(QuickTransferHandler={});
(function(){var a=function(){var a=JsCache.get("#quickTransferForm");PageConfig.quickTransferValidator=a.validate({errorClass:"help-block",highlight:function(a){$(a).closest("td").addClass("has-error")},unhighlight:function(a){$(a).closest("td").removeClass("has-error")}});a.find("[name=quickTransferFrom]").rules("add",{required:!0});a.find("[name=quickTransferTo]").rules("add",{required:!0});a.find("[name=quickTransferAmount]").rules("add",{required:!0,number:!0,moneyAmount:!0,messages:{required:I18N.get("msg.error.validation.requireAmount")}})},
b=function(a){a.preventDefault(a);var b=this;UiHandler.loading(b,!0);a=0;JsCache.get("#quickTransferAmount").valid()||a++;JsCache.get("#quickTransferFrom").valid()||a++;JsCache.get("#quickTransferTo").valid()||a++;var c=JsCache.get("#quickTransferFrom").val(),d=JsCache.get("#quickTransferTo").val(),e=JsCache.get("#quickTransferAmount").val();0>=e&&(DialogHandler.showAlert("form.text.error","msg.error.validation.requireAmount"),a++);c==d&&(DialogHandler.showAlert("form.text.error","msg.error.validation.canNotSelectSameProvider"),
a++);0<a?UiHandler.loading(b,!1):$.ajax({url:"/player/transfer?"+Math.random(),type:"POST",dataType:"json",data:{transferFrom:c,transferTo:d,transferAmount:e}}).done(function(a){var c=CurrencyType.getInstanceOf(PageConfig.playerCurrencyId),d=c.symbol+" "+CurrencyUtil.format(a.transferAmount),f=$("#quickTransferFrom option:selected").attr("data-code"),g=$("#quickTransferTo option:selected").attr("data-code"),h=$("#quickTransferTo option:selected").attr("data-name");if("BBIN"==g||"BBIN"==f)d=c.symbol+
" "+CurrencyUtil.format(e,{precision:0,separateSign:",",formatter:CurrencyUtil.formatter1,"trailingZeros,":!1,roundingMode:CurrencyUtil.roundingMode.DOWN});DialogHandler.showAlert("global.text.notification",a.message,[d,h]);"200"==a.status&&(PlayerHeaderHandler.manualRefreshBalance(),JsCache.get("#quickTransferAmount").val(""),JsCache.get("#quickTransferFrom").val(""),JsCache.get("#quickTransferTo").val(""));UiHandler.loading(b,!1)}).fail(function(a){Trace.error(a);UiHandler.loading(b,!1);DialogHandler.showErrorAlert()})};
QuickTransferHandler.init=function(){a();$("#ts-sign").on("click",function(){JsCache.get("#ts-whole").toggleClass("labas")});$("#submitQuickTransfer").on("click",b);$("#quickTransferFrom, #quickTransferTo").on("change",function(){$(this).find("option:selected").attr("data-code");JsCache.get("#quickTransferAmount").attr("data-scale","2");JsCache.get("#quickTransferAmount").valid()})}})();

