var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){a!=Array.prototype&&a!=Object.prototype&&(a[b]=e.value)};$jscomp.getGlobal=function(a){a=["object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+b++,e)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,c={next:function(){if(e<a.length){var d=e++;return{value:b(d,a[d]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill=function(a,b,e,c){if(b){e=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];d in e||(e[d]={});e=e[d]}a=a[a.length-1];c=e[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a,e){return e})}},"es8","es3");
$(document).ready(function(){$("#main-nav").find("ul li a").each(function(a,b){a=$(b);a.attr("href")===window.location.pathname&&a.addClass("active");"/"!==a.attr("href")||"/page/guest/guest.jsp"!==window.location.pathname&&"/page/player/player.jsp"!==window.location.pathname||a.addClass("active")})});
$(document).ready(function(){$("#new-nav").find("a").each(function(){$(this).attr("href")===window.location.pathname&&$(this).closest("li").addClass("on")});$(document).on("click",".spinit",function(){$(this).addClass("spin");setTimeout(function(){$(".spinit").removeClass("spin")},2E3)});$("#custAlertOuter .alert-overlay").click(function(){JsCache.get("#custAlertOuter .cust-alert").animate({"margin-top":"-100%",top:0},300,function(){JsCache.get("#custAlertOuter").animate({opacity:0},100,function(){JsCache.get("#custAlertOuter").hide()})});
$("#closeAlert").text(I18N.get("ui.text.btn_close"))});$("#closeAlert").click(function(){$(this).closest(".cust-alert").prev().click();$("#closeAlert").text(I18N.get("ui.text.btn_close"))});$(".close-modal").click(function(){$(this).closest(".container").prev().click()});$(".close-modal-alert").click(function(){$(this).closest(".cust-alert").prev().click()});$(".overlay").click(function(){if("small-game"!=this.parentNode.parentNode.className){var a=$(this.parentNode);$(this).next().animate({"margin-top":"-100%"},
300,function(){$(this).hide();$(a).animate({opacity:0},100,function(){$(a).hide()})});$(".content").scrollTop(0)}})});"undefined"==typeof InboxAlertHandler&&(InboxAlertHandler={});
(function(){var a,b=function(a,b){$("#inboxAlertTitle").text("you got a new message");$("#inboxAlertMessage").empty();$("#inboxAlertMessage").append(I18N.get(b));$("#inboxAlert").animate({right:"0"},1E3)},e=function(){$("#inboxAlert").animate({right:-1*$("#inboxAlert").outerWidth()},1E3)};InboxAlertHandler.autoShowHideAlert=function(c,d){b(c,d);a=setTimeout(function(){e()},15E3)};InboxAlertHandler.handleClose=function(){e();clearTimeout(a)}})();
function loading(a,b){b?($(a).data("loading-text","<i class='fa fa-circle-o-notch fa-spin fa-fw'></i>"),$(a).button("loading")):$(a).button("reset")}"undefined"==typeof PromotionHandler&&(PromotionHandler={});
(function(){function a(a,f,d){var h=DataBase.promotion.queryByID(a),c=d||null==h||"no"==h.dataPurchase;"no"!=$(f).attr("data-loading")&&loading(f,!0);h="/guest/getPromotionMessageDetail?";PageConfig.isLogin&&(h="/player/getPromotionMessageDetail?");d&&(h="/guest/getSliderDetail?",PageConfig.isLogin&&(h="/player/getSliderDetail?"));var k=!1;"yes"==$(f).attr("data-turnover")&&(k=!0);a+="";0<=a.indexOf("-")&&(a=a.split("-")[1]);$.ajax({url:h+Math.random(),type:"GET",dataType:"json",data:{id:a,forTurnover:k},
success:function(a){"no"!=$(f).attr("data-loading")&&loading(f,!1);a.contentType==MessageContentType.LINK.value?UiHandler.handleOpenUrl(a):null!=a.status&&500==a.status?(a.message?DialogHandler.showAlert("global.text.notification",a.message):DialogHandler.showAlert("global.text.notification","global.text.dataChanged"),JsCache.get("#closeAlert").on("mousedown",function(){location.reload()}),JsCache.get("#custAlertOuter .close-modal-alert").on("click",function(){location.reload()}),JsCache.get("#custAlertOuter .alert-overlay").on("click",
function(){location.reload()})):(b(a,c,d,PageConfig.webSiteType),k?(e(f),$("#turnover-detail-table").show()):$("#turnover-detail-table").hide())},error:function(a){"no"!=$(f).attr("data-loading")&&loading(f,!1);DialogHandler.showErrorAlert()}})}function b(a,b,d,c){if("tf"==c){b=$("#promo-detail");d=b.find(".remodal-title");d.find("h1").text(a.title);d.find("h3").text("");if(a.endDateTimeStr){c=a.endDateTimeStr.split(" ");var f=c[0].split("/"),h=c[1].lastIndexOf(":");d.find("h3").text(I18N.get("form.text.promotion.endTime",
[parseInt(f[0]),parseInt(f[1]),parseInt(f[2]),c[1].substring(0,h)]))}b.find(".remodal-content").html(a.webContent.replace("remodal-content",""));PromotionHandler.showTFPromotionDetailToPopup()}else""!=a.bannerPath&&JsCache.get("#promotion_banner").attr("src",PageConfig.cdnDomain+a.bannerPath),$("#promotion_note").empty(),$("#promotion_title").text(a.title),$("#promotion_title_separate").text(a.title),$("#promotion_summary_separate").text(d?"":a.description),$("#promotion_note").append(a.webContent),
c=0,null!=a.endDateTime&&(c=a.endDateTime-(new Date).getTime()),c=Math.ceil(c/1E3),1==a.id||d||0>=c?$("#promoClock").hide():($("#promoClock").show(),PromotionHandler.clock&&(PromotionHandler.clock.setTime(c),PromotionHandler.clock.start())),b?$("#show_bank, #trigger_show_bank").hide():($("#show_bank").show(),$("#trigger_show_bank").show(),$("#show_bank, #trigger_show_bank").attr("data-id",a.id).attr("data-bonustemplateid",a.bonusTemplateId).attr("data-title",a.title).attr("data-type",a.type).attr("data-min",
a.amountMin)),$("#promo-detail").show().css("z-index","6000").animate({opacity:1,"z-index":6E3},100,function(){JsCache.get("#promotion_note").parent().prop("scrollTop",0);$(this).find(".container").show().animate({"margin-top":"50px"},300)})}function e(a){var b=DataBase.turnover.queryByID(a.id);a=b.init_deposit;var d=b.bonus,c=b.requirement_turnover,h=b.completed,e=b.progress;b=b.create_time;$("#turnover-detail-amount").text(parseFloat(a).toLocaleString(void 0,{minimumFractionDigits:2}));$("#turnover-detail-bonus").text(parseFloat(d).toLocaleString(void 0,
{minimumFractionDigits:2}));$("#turnover-detail-required").text(parseFloat(c).toLocaleString(void 0,{minimumFractionDigits:2}));$("#turnover-detail-turnover").text(parseFloat(h).toLocaleString(void 0,{minimumFractionDigits:2}));$("#turnover-detail-completed").text(e+"%");$("#turnover-detail-date").text(b)}function c(a,b){a.overlay.removeClass("remodal-is-"+d.CLOSING+" remodal-is-"+d.OPENING+" remodal-is-"+d.CLOSED+" remodal-is-"+d.OPENED).addClass("remodal-is-"+b);a.detail.removeClass("remodal-is-"+
d.CLOSING+" remodal-is-"+d.OPENING+" remodal-is-"+d.CLOSED+" remodal-is-"+d.OPENED).addClass("remodal-is-"+b);a.modal.removeClass("remodal-is-"+d.CLOSING+" remodal-is-"+d.OPENING+" remodal-is-"+d.CLOSED+" remodal-is-"+d.OPENED).addClass("remodal-is-"+b)}PromotionHandler.clock=null;PromotionHandler.remodalObj={};PromotionHandler.initForNav=function(){const b=$("#promoClock");0<b.size()&&(PromotionHandler.clock=b.FlipClock(31536E3,{clockFace:"DailyCounter",countdown:!0,language:"chinese"}));$(document).on("click",
".trigger_more_promo",function(b){b.stopPropagation();var d=$(b.currentTarget).data("id");a(d,b.currentTarget,!1)});$(".trigger_more_slider").click(function(b){b.stopPropagation();var d=$(b.currentTarget).data("id");a(d,b.currentTarget,!0)});$(".trigger_more_promo_message").click(function(b){b.stopPropagation();var d=$(b.currentTarget).data("id");a(d,b.currentTarget,!1)});$(".image_more_promo").click(function(a){$(this).siblings(".trigger_more_promo").click()});$(document).on("click",".image_more_promo",
function(a){$(this).siblings(".trigger_more_promo").click()});$(document).on("click",".trigger_more_info",function(b){b.stopPropagation();var d=$(b.currentTarget).data("id");a(d,b.currentTarget,!1)});$.each($(document).find(".remodal-is-closed"),function(){var a=$(this).attr("name");PromotionHandler.remodalObj[a]=$(this)})};PromotionHandler.showMorePromo=function(b,d){a(b,d,!1)};PromotionHandler.showTurnoverDetail=function(a,b){a=DataBase.turnover.queryByID(b.id);$("#promoClock").hide();$("#promotion_note").empty();
$("#promotion_title").text(a.title);$("#promotion_title_separate").text(a.title);$("#promotion_summary_separate").text(a.summary);$("#promotion_note").append(a.summary);$("#show_bank, #trigger_show_bank").hide();$("#promo-detail").show().css("z-index","6000").animate({opacity:1,"z-index":6E3},100,function(){JsCache.get("#promotion_note").parent().prop("scrollTop",0);$(this).find(".container").show().animate({"margin-top":"50px"},300)});e(b);$("#turnover-detail-table").show()};var d={CLOSING:"closing",
CLOSED:"closed",OPENING:"opening",OPENED:"opened"};PromotionHandler.showTFPromotionDetailToPopup=function(){PromotionHandler.remodalObj.overlay.show();PromotionHandler.remodalObj.detail.show();c(PromotionHandler.remodalObj,d.OPENING);c(PromotionHandler.remodalObj,d.OPENED)};PromotionHandler.closeTFPromotionDetailToPopup=function(){PromotionHandler.remodalObj.overlay.hide();c(PromotionHandler.remodalObj,d.CLOSING);c(PromotionHandler.remodalObj,d.CLOSED);PromotionHandler.remodalObj.detail.hide()}})();
"undefined"==typeof DataBase&&(DataBase={});(function(){DataBase.promotion={};var a=new HashMap;DataBase.promotion.insert=function(b){a.put(b.id,b)};DataBase.promotion.remove=function(b){a.remove(b)};DataBase.promotion.queryByID=function(b){return a.get(b)};DataBase.promotion.queryAll=function(){return a.values()};DataBase.promotion.clean=function(){a.clear()}})();"undefined"==typeof PlayGameHandler&&(PlayGameHandler={});
(function(){var a=function(a){a=$(this).attr("data-vendor");var b=$(this).attr("data-href");null!=b&&0==b.indexOf("?t=")&&(b="/guest/viewGame"+b);"AG"!=a&&"GD"!=a&&"EBET"!=a&&$(this).attr("data-code");var c="width="+screen.width+", height="+(screen.height-100)+", bottom=0, right=0";"PG"==a&&(c=e());b&&window.open(b,"gametab0",c)},b=function(a){a.preventDefault(a);var b=$(this);if(!b.hasClass("trialPlayBtn")||!b.attr("data-href")){var c=localStorage.getItem("sgametab");null===c||""===c||"undefined"==
typeof c?(c=["","",""],localStorage.setItem("sgametab",JSON.stringify(c))):c=JSON.parse(localStorage.getItem("sgametab"));a=c;var f=b.attr("data-vendor"),k=b.attr("data-href");b.data("type")&&b.data("vendor")?(k="/player/playGame?t="+b.data("type")+"&v="+b.data("vendor"),b.data("code")&&(k+="&g="+b.data("code"))):k&&0===k.indexOf("?t=")&&(k="/player/playGame"+k);b=b.attr("data-code");if("AG"===f||"GD"===f||"EBET"===f)b=f;if(PageConfig.isLogin)if(PageConfig.accountStatus!==AccountStatusType.ACTIVE.unique())isNaN(PageConfig.accountStatus)?
DialogHandler.showAlert("global.text.notification",I18N.get("msg.error.account_status_invalid",[PageConfig.accountStatus])):AccountStatusType.INACTIVED.unique()===PageConfig.accountStatus?DialogHandler.showAlert("global.text.notification","msg.error.account.isInactived"):AccountStatusType.SUSPEND.unique()===PageConfig.accountStatus?DialogHandler.showAlert("global.text.notification","msg.error.account.isSuspended"):AccountStatusType.LOCKED.unique()===PageConfig.accountStatus?DialogHandler.showAlert("global.text.notification",
"msg.error.account.isLocked"):DialogHandler.showAlert("global.text.notification",I18N.get("msg.error.account_status_invalid",[PageConfig.accountStatus]));else{var l=0,m="gametab0",g=c.indexOf(b);if(-1!==g)l=g,m="gametab"+g;else for(g=2;0<=g;g--)""===a[g]&&(l=g,m="gametab"+g);g="width="+screen.width+", height="+(screen.height-100)+", bottom=0, right=0";if("PG"===f||"SBO"===f&&"604501"===b)g=e();a[l]=window.open(k,m,g);a[l].focus();c[l]=b;localStorage.setItem("sgametab",JSON.stringify(c))}else DialogHandler.showRegister()}},
e=function(){var a=window.outerHeight-window.innerHeight,b=window.screen.availHeight,e=window.safari||-1<navigator.userAgent.indexOf("OPR")||-1<navigator.userAgent.indexOf("Opera"),f=e?b:b-a;e=e?Math.floor((f-a)/16*9):Math.floor(f/16*9);return"left="+(window.screen.availWidth/2-e/2)+", top="+(window.screen.height-a-f-(window.screen.height-b))/2+", width="+e+", height="+f};PlayGameHandler.init=function(c){$(document).on("click","a[name=vendor], img[name=vendor], dd[name=vendor], button[name=vendor]",
b);$(document).on("click",".slotpage .playBtn",b);$(document).on("click",".slotpage .trialPlayBtn, .sport .trialPlayBtn",a)}})();"undefined"==typeof SportHandler&&(SportHandler={});
(function(){SportHandler.enterSportGame=function(a,b){var e="ESportsbull"===a?"ESport":"Sport";PageConfig.isLogin?window.open(`/player/playGame?t=${e}&v=${a}${b?`&act=${b}`:""}`):$.ajax({url:"/guest/viewGame",type:"POST",dataType:"json",data:{v:a,t:e,act:b},success:function(a){PageConfig.isLogin||a.url?null==a.url?DialogHandler.showAlert("global.text.notification",a.message):window.open(a.url):DialogHandler.showRegister()}})};SportHandler.clickHeaderTab=function(a){a=$(a).attr("data-href");PageConfig.isLogin||
""!=a?window.open(a):DialogHandler.showRegister()};SportHandler.clickSportSlider=function(a){a=$(a);var b=DataBase.msg.queryByID(a.attr("data-id"));null!=b&&b.contentType==MessageContentType.LINK.value?(a="#",b=b.webContent,-1==b.indexOf("href=")?a=b.replace("<p>","").replace("</p>",""):(b=b.match(/href="[^"]+"/g),0<b.length&&(a=b[0].replace("href=","").replace(/"/g,""))),a=a.replace(/&amp;/g,"&"),PageConfig.isLogin||-1===a.indexOf("/player/playGame")&&-1===a.indexOf("/exchange/member/")?(a=PageConfig.isLogin?
a.replace("/guest/","/player/"):a.replace("/player/","/guest/"),a=a.replace("/h5/","/page/"),window.open(a)):DialogHandler.showRegister()):DialogHandler.showMessageDetail(b)}})();"undefined"==typeof UiHandler&&(UiHandler={});
(function(){UiHandler.loading=function(a,b){b?(a.disabled=!0,$(a).data("loading-text",'<i class="fa fa-circle-o-notch fa-spin fa-fw"></i>'),$(a).button("loading")):(a.disabled=!1,$(a).button("reset"))};UiHandler.handleOpenUrl=function(a){var b="#";a=a.webContent;-1===a.indexOf("href=")?b=a.replace("<p>","").replace("</p>",""):(a=a.match(/href="[^"]+"/g),0<a.length&&(b=a[0].replace("href=","").replace(/"/g,"")));b=b.replace(/&amp;/g,"&");b=PageConfig.isLogin?b.replace("/guest/","/player/"):b.replace("/player/",
"/guest/");b=b.replace("/h5/","/page/");0===b.indexOf("/")&&-1===b.indexOf("/player/playGame")?location.href=b:"#"!==b&&window.open(b)}})();

