if(PageConfig.tracking[PageConfig.webSiteType]["gtm.code"]&&(function(a,b,c,d,e){a[d]=a[d]||[];a[d].push({"gtm.start":(new Date).getTime(),event:"gtm.js"});a=b.getElementsByTagName(c)[0];b=b.createElement(c);b.async=!0;b.src="https://www.googletagmanager.com/gtm.js?id="+e+("dataLayer"!=d?"&l="+d:"");a.parentNode.insertBefore(b,a)}(window,document,"script","dataLayer",PageConfig.tracking[PageConfig.webSiteType]["gtm.code"]),PageConfig.tracking[PageConfig.webSiteType]["gtm.tracking"])){var clearUnNotifiedTxn=
function(b){$.ajax({url:"/player/clearUnNotifiedTxn",type:"POST",dataType:"json",data:{timestamp:b},success:function(a){},error:function(a){}})},getUnNotifiedTxn=function(){$.ajax({url:"/player/getUnNotifiedTxn",type:"POST",dataType:"json",success:function(b){if(b.detail&&0<b.detail.length){for(let c=0;b.detail.length>c;c++){let d=b.detail[c];a(PageConfig.userId,d.amount,PageConfig.currencyName,d.isFirst,d.paymentMethod,d.approveTime)}clearUnNotifiedTxn(b.timestamp)}},error:function(a){},complete:function(){setTimeout(getUnNotifiedTxn,
3E5)}})};window.dataLayer=window.dataLayer||[];"undefined"==typeof GtmTrackingHandler&&(GtmTrackingHandler={});GtmTrackingHandler.completeRegistration=function(b,c){b&&dataLayer.push({event:"registrationCompleted",eventCategory:"Registration",eventAction:"Submit",eventLabel:"Registration Form Submit",pageUrl:window.location.href,userId:b,currency:c,registerDate:DateUtil.format(new Date,"yyyyMMdd"),registrationStatus:"success"})};PageConfig.isLogin&&setTimeout(getUnNotifiedTxn,5E3);let a=function(b,
c,d,e,f,g){if(b){g=new Date(g);let a="depositCompleted",h="Deposit Submit";e&&(a="firstDepositCompleted",h="First Deposit Submit");dataLayer.push({event:a,eventCategory:"Deposit",eventAction:"Submit",eventLabel:h,paymentMethod:f,pageUrl:window.location.href,depositValue:c,currency:d,userId:b,depositDate:DateUtil.format(g,"yyyyMMdd"),depositStatus:"success"})}}}
if(PageConfig.tracking[PageConfig.webSiteType]["hm.baidu.code"]){var _hmt=_hmt||[];(function(){var a=document.createElement("script");a.async=1;a.src="https://hm.baidu.com/hm.js?"+PageConfig.tracking[PageConfig.webSiteType]["hm.baidu.code"];var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})()}
PageConfig.tracking[PageConfig.webSiteType]._hjSettings&&function(a,b,c,d,e,f){a.hj=a.hj||function(){(a.hj.q=a.hj.q||[]).push(arguments)};a._hjSettings=PageConfig.tracking[PageConfig.webSiteType]._hjSettings;e=b.getElementsByTagName("head")[0];f=b.createElement("script");f.async=1;f.src=c+a._hjSettings.hjid+d+a._hjSettings.hjsv;e.appendChild(f)}(window,document,"https://static.hotjar.com/c/hotjar-",".js?sv=");
PageConfig.tracking[PageConfig.webSiteType].gaCode&&JSON.parse(PageConfig.tracking[PageConfig.webSiteType].gaCode).forEach(a=>{function b(){dataLayer.push(arguments)}window.dataLayer=window.dataLayer||[];b("js",new Date);b("config",a)});
PageConfig.tracking[PageConfig.webSiteType]["gaCode.pageview"]&&(function(a,b,c,d,e,f,g){a.GoogleAnalyticsObject=e;a[e]=a[e]||function(){(a[e].q=a[e].q||[]).push(arguments)};a[e].l=1*new Date;f=b.createElement(c);g=b.getElementsByTagName(c)[0];f.async=1;f.src=d;g.parentNode.insertBefore(f,g)}(window,document,"script","https://www.google-analytics.com/analytics.js","ga"),ga("create",PageConfig.tracking[PageConfig.webSiteType]["gaCode.pageview"],"auto"),ga("send","pageview"));
PageConfig.tracking[PageConfig.webSiteType]["clarity.ms"]&&function(a,b,c,d,e,f,g){a[c]=a[c]||function(){(a[c].q=a[c].q||[]).push(arguments)};f=b.createElement(d);f.async=1;f.src="https://www.clarity.ms/tag/"+e;g=b.getElementsByTagName(d)[0];g.parentNode.insertBefore(f,g)}(window,document,"clarity","script",PageConfig.tracking[PageConfig.webSiteType]["clarity.ms"]);
PageConfig.tracking[PageConfig.webSiteType].appier&&function(a,b,c,d,e,f,g){window.location.host===e&&(a.appier_q=a.appier_q||[],a.appier_q.push({t:"register",content:{id:"9862",site:e}}),a.appier_q.push({t:"pv_track",action_id:"PageView_1147",track_id:"947bf0d9dd78a6d",isCountReload:!0,counter:0},{t:"pv_track",action_id:"ViewTwoPages_b807",track_id:"947bf0d9dd78a6d",isCountReload:!1,counter:1}),PageConfig.tracking[PageConfig.webSiteType].affiliateLink===window.location.pathname&&a.appier_q.push({t:"type_landing",
action_id:"ViewLanding_b39e",track_id:"947bf0d9dd78a6d",opts:{unique_key:"true"}}),"#registerSuccess"===window.location.hash&&PageConfig.tracking[PageConfig.webSiteType].affiliateCode===PageConfig.affiliateCode&&a.appier_q.push({t:"type_conversion",content:"submit",action_id:"Conversion_e694",track_id:"947bf0d9dd78a6d",opts:{unique_key:"true"}}),f=b.createElement(c),g=b.getElementsByTagName(c)[0],f.async=1,f.src=d,g.parentNode.insertBefore(f,g))}(window,document,"script","//jscdn.appier.net/aa.js?id=panalobet.club",
PageConfig.tracking[PageConfig.webSiteType].appier);
if(PageConfig.tracking&&PageConfig.tracking[PageConfig.webSiteType]&&PageConfig.tracking[PageConfig.webSiteType].sportRadarId){var encode=function(a){return window.btoa(a).replace("=","")};"undefined"==typeof SportradarHandler&&(SportradarHandler={});(function(a,b,c,d,e,f){a[e]=a[e]||[];a.x=b.createElement(c);a.y=b.getElementsByTagName(c)[0];x.src=d+"?id="+f;x.setAttribute("data-srtmn",e);y.parentNode.insertBefore(x,y)})(window,document,"script","https://tm.ads.sportradar.com/dist/tag-manager.js",
"srtmCommands",PageConfig.tracking[PageConfig.webSiteType].sportRadarId);SportradarHandler.initRegistration=function(){srtmCommands.push({event:"track.user.registration",payload:{action:"start"}})};SportradarHandler.completeRegistration=function(a){a&&(a=encode(a),srtmCommands.push({event:"track.user.registration",payload:{action:"complete",userId:a}}))};SportradarHandler.loginSuccess=function(a){a&&(a=encode(a),srtmCommands.push({event:"track.user.login",payload:{action:"complete",userId:a}}))};
SportradarHandler.depositSuccess=function(a,b,c,d,e){a={action:"created",userId:a,transactionId:e,amount:b,currency:c};PageConfig.firstDepositTime&&(a.label="first_deposit");srtmCommands.push({event:"track.betting.deposit",payload:a})}}
PageConfig.tracking&&PageConfig.tracking[PageConfig.webSiteType]&&PageConfig.tracking[PageConfig.webSiteType].registerSuccessUrl&&("undefined"==typeof RegisterSuccessHandler&&(RegisterSuccessHandler={}),!sessionStorage.getItem("registerSuccessCID")&&new URLSearchParams(window.location.search)&&(new URLSearchParams(window.location.search)).get("cid")&&-1<window.location.href.indexOf("/af/")&&sessionStorage.setItem("registerSuccessCID",(new URLSearchParams(window.location.search)).get("cid")),RegisterSuccessHandler.completeRegistration=
function(){sessionStorage.getItem("registerSuccessCID")&&fetch(PageConfig.tracking[PageConfig.webSiteType].registerSuccessUrl+"?cid="+sessionStorage.getItem("registerSuccessCID")).then(a=>a.text()).then(a=>console.log(a)).catch(a=>{console.log("register tracking error")})});
if(PageConfig.tracking&&PageConfig.tracking[PageConfig.webSiteType]&&PageConfig.tracking[PageConfig.webSiteType].rooterTrackingUrl){var send=function(a){fetch(a).then(a=>a.text()).then(a=>console.log(a)).catch(a=>{console.log("rooter tracking error")})};"undefined"==typeof RooterTrackingHandler&&(RooterTrackingHandler={});!sessionStorage.getItem("rooterclickid")&&new URLSearchParams(window.location.search)&&(new URLSearchParams(window.location.search)).get("rooterclickid")&&-1<window.location.href.indexOf("/af/")&&
sessionStorage.setItem("rooterclickid",(new URLSearchParams(window.location.search)).get("rooterclickid"));RooterTrackingHandler.completeRegistration=function(){sessionStorage.getItem("rooterclickid")&&send(PageConfig.tracking[PageConfig.webSiteType].rooterTrackingUrl+"?clickid="+sessionStorage.getItem("rooterclickid"))};RooterTrackingHandler.depositSuccess=function(){sessionStorage.getItem("rooterclickid")&&send(PageConfig.tracking[PageConfig.webSiteType].rooterTrackingUrl+"?goal=4&clickid="+sessionStorage.getItem("rooterclickid"))}}
if(PageConfig.tracking&&PageConfig.tracking[PageConfig.webSiteType]&&PageConfig.tracking[PageConfig.webSiteType].sharechatTrackingUrl){var send$jscomp$1=function(a){fetch(a).then(a=>a.text()).then(a=>console.log(a)).catch(a=>{console.log("sharechat tracking error")})};"undefined"==typeof SharechatTrackingHandler&&(SharechatTrackingHandler={});!sessionStorage.getItem("sharechatclickid")&&new URLSearchParams(window.location.search)&&(new URLSearchParams(window.location.search)).get("sharechatclickid")&&
-1<window.location.href.indexOf("/af/")&&sessionStorage.setItem("sharechatclickid",(new URLSearchParams(window.location.search)).get("sharechatclickid"));!sessionStorage.getItem("sharechatadid")&&new URLSearchParams(window.location.search)&&(new URLSearchParams(window.location.search)).get("sharechatadid")&&-1<window.location.href.indexOf("/af/")&&sessionStorage.setItem("sharechatadid",(new URLSearchParams(window.location.search)).get("sharechatadid"));SharechatTrackingHandler.completeRegistration=
function(){sessionStorage.getItem("sharechatclickid")&&sessionStorage.getItem("sharechatadid")&&send$jscomp$1(PageConfig.tracking[PageConfig.webSiteType].sharechatTrackingUrl+"?eventName=registration&eventValue=1&clickId="+sessionStorage.getItem("sharechatclickid")+"&adId="+sessionStorage.getItem("sharechatadid"))};SharechatTrackingHandler.depositSuccess=function(a,b){sessionStorage.getItem("sharechatclickid")&&sessionStorage.getItem("sharechatadid")&&send$jscomp$1(PageConfig.tracking[PageConfig.webSiteType].sharechatTrackingUrl+
"?eventName=transaction&eventValue="+b+"&userId="+a+"&clickId="+sessionStorage.getItem("sharechatclickid")+"&adId="+sessionStorage.getItem("sharechatadid"))}}
;
