"undefined"==typeof StringUtil&&(StringUtil={});
(function(){StringUtil.startsWith=function(b,a){return b.substr(0,a.length)==a};StringUtil.endsWith=function(b,a){return b.substring(b.length-a.length)==a};StringUtil.concat=function(b,a){return new String(b.toString()+a)};StringUtil.toCharArray=function(b){for(var a=Array(b.length),c=0;c<b.length;c++)a[c]=b.charAt(c);return a};StringUtil.trim=function(b){return b.replace(/(^\s*)|(\s*$)/g,"")};StringUtil.replaceAll=function(b,a,c){for(var d=b.indexOf(a);-1!=d;)b=b.replace(a,c),d=b.indexOf(a);return b};
StringUtil.isOnlyLowerCaseLetterAndNumber=function(b){return/^[\d|a-z]+$/.test(b)?!0:!1};StringUtil.isOnlyNumber=function(b){return/^[\d]+$/.test(b)?!0:!1};StringUtil.isOnlyNumberAndColon=function(b){return/^[\d:]+$/.test(b)?!0:!1};StringUtil.makeRandom=function(b){for(var a="",c=0;c<b;c++)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*Math.random()));return a};StringUtil.format=function(b,a){b=b.toString()||"";return"undefined"!==typeof a&&null!=a&&0<a.length?
String(b).replace(new RegExp("{([0-"+a.length+"])}","g"),function(c,b){return a[b]}):b};StringUtil.isString=function(b){return"string"===typeof b}})();"undefined"==typeof ArrayUtil&&(ArrayUtil={});
(function(){ArrayUtil.max=function(b){var a,c=b[0];for(a=1;a<b.length;a++)c<b[a]&&(c=b[a]);return c};ArrayUtil.contains=function(b,a){for(var c=0;c<b.length;c++)if(b[c]===a)return!0;return!1};ArrayUtil.remove=function(b,a){for(var c=0;c<b.length;c++)if(b[c]===a)return b.splice(c,1),!0;return!1};ArrayUtil.isArray=function(b){return"[object Array]"===Object.prototype.toString.call(b)};ArrayUtil.distinct=function(b){for(var a=[],c=0,d=b.length;c<d;c++){var e=0;for(len=a.length;e<len&&b[c]!==a[e];e++);
e==a.length&&a.push(b[c])}return a}})();
function HashMap(){this.length=0;this.elements={};this.size=function(){return this.length};this.put=function(b,a){this.elements.hasOwnProperty(b)||this.length++;this.elements[b]=a};this.putAll=function(b){for(var a in b)this.elements.hasOwnProperty(a)||this.length++,this.elements[a]=b[a]};this.remove=function(b){return this.elements.hasOwnProperty(b)?(this.length--,delete this.elements[b],!0):!1};this.containsKey=function(b){return this.elements.hasOwnProperty(b)};this.get=function(b){return this.elements.hasOwnProperty(b)?
this.elements[b]:null};this.values=function(){var b=Array(this.length),a=0,c;for(c in this.elements)b[a++]=this.elements[c];return b};this.entrySet=function(){var b=Array(this.length),a=0,c;for(c in this.elements)b[a++]={key:c,value:this.elements[c]};return b};this.clear=function(){this.elements={};this.length=0};this.keySet=function(){var b=Array(this.length),a=0,c;for(c in this.elements)b[a++]=c;return b}}"undefined"==typeof DateUtil&&(DateUtil={});
(function(){var b={1:"JAN",2:"FEB",3:"MAR",4:"APR",5:"MAY",6:"JUN",7:"JUL",8:"AUG",9:"SEP",10:"OCT",11:"NOV",12:"DEC"};DateUtil.format=function(a,c){a=a?new Date(a):new Date;if(isNaN(a))throw SyntaxError("invalid date");c=c.replace(/yyyy/i,a.getFullYear());var d=a.getMonth()+1;c=c.replace(/MMM/,b[d]);c=c.replace(/MM/,10>d?"0"+d:d);d=a.getDate();c=c.replace(/dd/,10>d?"0"+d:d);d=a.getHours();c=c.replace(/hh/i,10>d?"0"+d:d);c=c.replace(/TT/,12>d?"AM":"PM");d=a.getMinutes();c=c.replace(/mm/,10>d?"0"+
d:d);d=a.getSeconds();return c=c.replace(/ss/,10>d?"0"+d:d)};DateUtil.countTime=function(a,c){c.setTime(c.getTime()+6E4);a.html(DateUtil.format(c,"MM/dd/yyyy hh:mm")+" GMT+8");setTimeout(function(){DateUtil.countTime(a,c)},6E4)};DateUtil.showTime=function(a){var c=new Date(PageConfig.serverCurrentTimeMillis);a.html(DateUtil.format(c,"MM/dd/yyyy hh:mm")+" GMT+8");var b=c.getSeconds();c.setTime(c.getTime()-1E3*b);setTimeout(function(){DateUtil.countTime(a,c)},1E3*(60-b))};DateUtil.compare=function(a,
c){return isFinite(a=DateUtil.convert(a).valueOf())&&isFinite(c=DateUtil.convert(c).valueOf())?(a>c)-(a<c):NaN};DateUtil.convert=function(a){return a.constructor===Date?a:a.constructor===Array?new Date(a[0],a[1],a[2]):a.constructor===Number?new Date(a):a.constructor===String?new Date(a):"object"===typeof a?new Date(a.year,a.month,a.date):NaN};DateUtil.getDateFormat=function(a){from=a.split("/");return new Date(from[2],from[1]-1,from[0])}})();"undefined"==typeof CurrencyUtil&&(CurrencyUtil={});
(function(){function b(a,c,b,e){if(e)return CurrencyUtil.roundingMode.DOWN==e?0>a?CurrencyUtil.thousandComma((Math.ceil((a*Math.pow(10,c)).toFixed(1))/Math.pow(10,c)).toFixed(c)):CurrencyUtil.thousandComma((Math.floor((a*Math.pow(10,c)).toFixed(1))/Math.pow(10,c)).toFixed(c)):CurrencyUtil.roundingMode.HALF_UP==e?(e=0>a?-1:1,a=(e*a*Math.pow(10,c)).toString(),c=(e*(Math.round(a.substring(0,a.split(".")[0].length+2))/Math.pow(10,c))).toFixed(c),b&&(c=CurrencyUtil.thousandComma(c)),c):0;c=isNaN(c=Math.abs(c))?
2:c;b=void 0==b?",":b;s=0>a?"-":"";i=parseInt(a=Math.abs(+a||0).toFixed(c))+"";j=3<(j=i.length)?j%3:0;return s+(j?i.substr(0,j)+b:"")+i.substr(j).replace(/(\d{3})(?=\d)/g,"$1"+b)+(c?"."+Math.abs(a-i).toFixed(c).slice(2):"")}CurrencyUtil.roundingMode={};CurrencyUtil.roundingMode.DOWN="DOWN";CurrencyUtil.roundingMode.HALF_UP="HALF_UP";CurrencyUtil.locales="en-US";CurrencyUtil.formatSetting={maximumFractionDigits:2};CurrencyUtil.format=function(a,c){"undefined"!==typeof FE&&FE.PageConfig.balanceLocale&&
(CurrencyUtil.locales=FE.PageConfig.balanceLocale);c&&(CurrencyUtil.formatSetting=c);c=(new String(a)).replace(/,/g,"");return CurrencyUtil.isNumber(c)?0>c?'<span style="color: red;">('+Math.abs(parseFloat(c)).toLocaleString(CurrencyUtil.locales,CurrencyUtil.formatSetting)+")</span>":parseFloat(c).toLocaleString(CurrencyUtil.locales,CurrencyUtil.formatSetting):a};CurrencyUtil.isNumber=function(a){return"NaN"==parseFloat(a).toString()?!1:!0};CurrencyUtil.isNumeric=function(a,c,b){var d=!0,f=0,k="0123456789";
c&&(k+=".");b&&(k+="-");for(var g,h=0;h<a.length&&1==d;h++){g=a.charAt(h);b&&"-"==g&&0<h&&(d=!1);if(c&&"."==g){f+=1;if(0==h||h==a.length-1)d=!1;1<f&&(d=!1)}-1==k.indexOf(g)&&(d=!1)}return d};CurrencyUtil.formatter2=function(a){return 0==a.indexOf("-")?"<span style='color:red'>"+a+"</span>":a};CurrencyUtil.formatter1=function(a){return 0==a.indexOf("-")?"<span style='color:red'>( "+a.substr(1)+" )</span>":a};CurrencyUtil.setting={precision:2,separateSign:",",formatter:CurrencyUtil.formatter1,"trailingZeros,":!1,
roundingMode:CurrencyUtil.roundingMode.HALF_UP};CurrencyUtil.setting2={precision:2,separateSign:",",formatter:CurrencyUtil.formatter2,"trailingZeros,":!1,roundingMode:CurrencyUtil.roundingMode.HALF_UP};CurrencyUtil.updateSetting=function(a){for(var c in a)if(a.hasOwnProperty(c))if("precision"==c){var b=a[c];0===b%1&&-1<b&&(CurrencyUtil.setting[c]=b)}else CurrencyUtil.setting[c]=a[c]};CurrencyUtil.formatter=function(a,c){c=void 0==c?CurrencyUtil.setting:c;a=b(a,c.precision,c.separateSign,c.roundingMode);
return c.formatter(a)};CurrencyUtil.thousandComma=function(a){a=a.toString().split(".");for(var c=/(-?\d+)(\d{3})/;c.test(a[0]);)a[0]=a[0].replace(c,"$1,$2");return a[1]?a[0]+"."+a[1]:a[0]};CurrencyUtil.getFormatter=function(a){var c={},b={},e;for(e in CurrencyUtil.setting)b[e]=a.hasOwnProperty(e)?a[e]:CurrencyUtil.setting[e];c.setting=b;c.format=function(a){return CurrencyUtil.formatter(a,c.setting)};return c}})();"undefined"==typeof MathUtil&&(MathUtil={});
(function(){MathUtil.decimal={};MathUtil.decimal.createDecimalSet=function(a,c,b){for(var d=[];a<=c;a=MathUtil.decimal.add(a,b))d.push(a);return d};MathUtil.decimal.add=function(a,c){if(null==a||0==a.length)a=0;if(null==c||0==c.length)c=0;try{var d=a.toString().split(".")[1].length}catch(f){d=0}try{var e=c.toString().split(".")[1].length}catch(f){e=0}d=Math.pow(10,Math.max(d,e));return(b(a,d)+b(c,d))/d};MathUtil.decimal.subtract=function(a,c){if(null==a||0==a.length)a=0;if(null==c||0==c.length)c=
0;try{var d=a.toString().split(".")[1].length}catch(f){d=0}try{var e=c.toString().split(".")[1].length}catch(f){e=0}d=Math.pow(10,Math.max(d,e));return(b(a,d)-b(c,d))/d};MathUtil.decimal.multiply=function(a,c){if(null==a||0==a.length)a=0;if(null==c||0==c.length)c=0;return b(a,c)};MathUtil.decimal.divide=function(a,c){var d=0,e=0;try{d=a.toString().split(".")[1].length}catch(f){}try{e=c.toString().split(".")[1].length}catch(f){}a=Number(a.toString().replace(".",""));c=Number(c.toString().replace(".",
""));return b(a/c,Math.pow(10,e-d))};MathUtil.isInteger=function(a){return null==a.match(/^\d+$/)?!1:!0};MathUtil.isNumeric=function(a,c,b){var d=!0,f=0,k="0123456789";c&&(k+=".");b&&(k+="-");if(0==a.length||1==a.length&&"-"==a.charAt(0))return!1;for(var g=0;g<a.length&&1==d;g++){var h=a.charAt(g);b&&"-"==h&&0<g&&(d=!1);if(c&&"."==h){f+=1;if(0==g||g==a.length-1)d=!1;1<f&&(d=!1)}-1==k.indexOf(h)&&(d=!1)}return d};MathUtil.isPositive=function(a){-1<a.toString().indexOf(",")&&(a=parseInt(StringUtil.replaceAll(a,
",","")));return 0<=a};MathUtil.roundp=function(a,c){c=Math.pow(10,c);return Math.round(a*c)/c};MathUtil.floor=function(a,c){c=Math.pow(10,c);return Math.floor(a*c)/c};MathUtil.ceil=function(a,c){c=Math.pow(10,c);return Math.ceil(a*c)/c};var b=function(a,c){var b=0,e=0;a=a.toString();var f=c.toString();try{b=a.split(".")[1].length}catch(k){}try{e=f.split(".")[1].length}catch(k){}c=Number(a.toString().replace(".",""));a=Number(f.toString().replace(".",""));return c*a/Math.pow(10,b+e)}})();
"undefined"==typeof TaskExecuter&&(TaskExecuter={});(function(){var b=[],a=null;TaskExecuter.execute=function(){0!=b.length?(a=b.pop(),a.execute()):setTimeout(TaskExecuter.execute,500)};TaskExecuter.addTask=function(a){b.push(a)};TaskExecuter.reExecute=function(){a.execute()}})();"undefined"==typeof TaskHelper&&(TaskHelper={});
(function(){TaskHelper.createTask=function(b,a,c,d){return{cycleTime:b,cycleTick:a,winType:c,execute:d,run:function(){this.cycleTick=this.cycleTime;TaskExecuter.addTask(this)},check:function(){if(!(0>this.cycleTick)){var a=this;0==this.cycleTick?(this.cycleTick=-1,setTimeout(function(){a.run()},100)):0<this.cycleTick&&(this.cycleTick--,setTimeout(function(){a.check()},1E3))}},refresh:function(){this.cycleTick=0}}}})();"undefined"==typeof I18N&&(I18N={});
(function(){var b=void 0;I18N.setResource=function(a){b=a};I18N.get=function(a,c){var d=a=a.toString()||"";"undefined"!==typeof b&&(d=b[a]?b[a]:a);return"undefined"!==typeof c&&null!=c&&0<c.length?String(d).replace(new RegExp("{([0-"+c.length+"])}","g"),function(a,b){return c[b]}):d}})();"undefined"==typeof JsCache&&(JsCache={});
(function(){var b={};JsCache.get=function(a){if(null==a||0==a.length)return null;var c=b[a];if(!c){c=$(a);if(0==c.length)return;b[a]=c}return c};JsCache.clone=function(a){a=JsCache.get(a);return null==a?null:a.clone()};JsCache.removeCache=function(a){if(null==a||0==a.length)return null;b[a]=null}})();"undefined"==typeof WindowEventUtil&&(WindowEventUtil={});
(function(){WindowEventUtil.stopEvent=function(b,a,c){b||(b=window.event);a||c||(c=a=!0);a&&(b.stopPropagation?b.stopPropagation():b.cancelBubble=!0);c&&(b.preventDefault?b.preventDefault():b.returnValue=!1);return!1}})();"undefined"==typeof KeyEventUtils&&(KeyEventUtils={});
(function(){KeyEventUtils.isNumberKey=function(b){var a=b.which||b.keyCode;return!b.shiftKey&&(47<a&&58>a||95<a&&106>a)};KeyEventUtils.isBackspaceKey=function(b){return 8===b};KeyEventUtils.isDeleteKey=function(b){return 46===b};KeyEventUtils.isEnterKey=function(b){return 13===b};KeyEventUtils.isShiftKey=function(b){return 16===b};KeyEventUtils.isCtrlKey=function(b){return 17===b};KeyEventUtils.isAltKey=function(b){return 18===b};KeyEventUtils.isArrowKey=function(b){return 36<b&&41>b};KeyEventUtils.isF5Key=
function(b){return 116==b};KeyEventUtils.isTabKey=function(b){return 9==b};KeyEventUtils.isDecimalPointKey=function(b){return 110==b||190==b};KeyEventUtils.isSubtractKey=function(b){var a=b.which||b.keyCode;return!b.shiftKey&&(109==a||189==a||173==a)};KeyEventUtils.isSpaceKey=function(b){return 32==b};KeyEventUtils.isAlphabetKey=function(b){return 64<b&&91>b};KeyEventUtils.isParenthesis=function(b){var a=b.which||b.keyCode;return b.shiftKey&&(57==a||48==a)};KeyEventUtils.isIME=function(b){return 229==
b};KeyEventUtils.isRefresh=function(b){var a=b.which||b.keyCode;return KeyEventUtils.isF5Key(a)||82==a&&b.ctrlKey}})();"undefined"==typeof FormatUtil&&(FormatUtil={});(function(){FormatUtil={padLeft:function(b,a,c){return Array(a-String(b).length+1).join(c||"0")+b}}})();"undefined"==typeof PageInfoHandler&&(PageInfoHandler={});
(function(){var b=0,a=10,c=1;PageInfoHandler.getTotalCount=function(){return b};PageInfoHandler.getPageSize=function(){return a};PageInfoHandler.getPageNumber=function(){return c};PageInfoHandler.setTotalCount=function(a){b=a};PageInfoHandler.setPageSize=function(b){a=b};PageInfoHandler.setPageNumber=function(a){c=a};PageInfoHandler.getTotalPage=function(){var c=parseInt(b/a);0<b%a&&c++;return c};PageInfoHandler.getFirstRowNumber=function(){return a*(c-1)};PageInfoHandler.getLastRowNumber=function(){return a*
c}})();"undefined"==typeof VipIconUtil&&(VipIconUtil={});
(function(){var b={yb:{showHiddenStar:!0},ld:{showHiddenStar:!1}},a={yb:[{group:0,icon:""},{group:1,icon:"star.png"}],ld:[{group:0,icon:""},{group:1,icon:"",gradeSetting:[{grade:0,icon:""},{grade:1,icon:"star.png"},{grade:2,icon:"bronze.png"},{grade:3,icon:"silver.png"},{grade:4,icon:"blue.png"},{grade:5,icon:"gold.png"}]}],tf:[{group:0,icon:""},{group:1,icon:"",gradeSetting:[{grade:0,icon:""},{grade:1,icon:"dragon0.png"},{grade:2,icon:"dragon1.png"},{grade:3,icon:"dragon2.png"},{grade:4,icon:"dragon3.png"},
{grade:5,icon:"dragon4.png"},{grade:6,icon:"dragon5.png"}]}],bv:[{group:0,icon:""},{group:1,icon:"",gradeSetting:[{grade:0,icon:""},{grade:1,icon:"silver.png"},{grade:2,icon:"gold.png"},{grade:3,icon:"platinum.png"},{grade:4,icon:"diamond.png"},{grade:5,icon:"silverLv5.png"}]}],vb:[{group:0,icon:""},{group:1,icon:"",gradeSetting:[{grade:0,icon:""},{grade:1,icon:"vip/vip1.png"},{grade:2,icon:"vip/vip2.png"},{grade:3,icon:"vip/vip3.png"},{grade:4,icon:"vip/vip4.png"}]}]};VipIconUtil.getIcon=function(b){var c=
a[PageConfig.webSiteType];if(null==c)return"star.png";var e="";null!=c[1]&&(e=c[1].icon,null!=c[1].gradeSetting&&(c=c[1].gradeSetting,null!=c[b]&&(e=c[b].icon)));return"bv"==PageConfig.webSiteType?PageConfig.lang+"-"+e:e};VipIconUtil.needShowHiddenStar=function(){return null==b[PageConfig.webSiteType]?!0:0!=b[PageConfig.webSiteType].showHiddenStar}})();"undefined"==typeof ReportUtil&&(ReportUtil={});
(function(){ReportUtil.setDefConditionOfTimeRange=function(b,a){var c=new Date,d=DateUtil.format(c,"yyyy/MM/dd");$("#"+a).val(d);a=DateUtil.format(c.setDate(c.getDate()-7),"yyyy/MM/dd");$("#"+b).val(a)};ReportUtil.setDefConditionOfTimeRangeByDOM=function(b,a){var c=new Date,d=DateUtil.format(c,"yyyy/MM/dd");a.val(d);a=DateUtil.format(c.setDate(c.getDate()-7),"yyyy/MM/dd");b.val(a)};ReportUtil.setDefPaymentConditionOfTimeRange=function(b,a){var c=new Date;c.setHours(23,59,59,999);var d=DateUtil.format(c,
"yyyy/MM/dd HH:mm:ss");$("#"+a).val(d);c.setHours(0,0,0,0);a=DateUtil.format(c.setDate(c.getDate()-1),"yyyy/MM/dd HH:mm:ss");$("#"+b).val(a)};ReportUtil.setDefPaymentConditionOfTimeRangeByDom=function(b,a){var c=new Date;c.setHours(23,59,59,999);var d=DateUtil.format(c,"yyyy/MM/dd HH:mm:ss");a.val(d);c.setHours(0,0,0,0);a=DateUtil.format(c.setDate(c.getDate()-1),"yyyy/MM/dd HH:mm:ss");b.val(a)};ReportUtil.validationMaxDate=function(b,a){$("#"+b).on("blur",function(){var b=$(this).val();0<DateUtil.compare(b,
a)&&$(this).val("")})};ReportUtil.validationMinDate=function(b,a){$("#"+b).on("blur",function(){var b=$(this).val();0>DateUtil.compare(b,a)&&$(this).val("")})};ReportUtil.validationMaxDateByDOM=function(b,a){b.on("blur",function(){var b=$(this).val();0<DateUtil.compare(b,a)&&$(this).val("")})};ReportUtil.validationMinDateByDOM=function(b,a){b.on("blur",function(){var b=$(this).val();0>DateUtil.compare(b,a)&&$(this).val("")})}})();"undefined"==typeof CheckBoxUtil&&(CheckBoxUtil={});
(function(){CheckBoxUtil.bindCheckAll=function(b,a,c){b=b.target.value;var d=$("[name="+a+"]");a=$("[name="+a+"][value=-1]");-1==b?a.prop("checked")?d.not(a).prop("checked",!0):d.not(a).prop("checked",!1):$("[name=gameType]:checked").not(a).length!==c?a.prop("checked",!1):a.prop("checked",!0);d.uniform()}})();"undefined"==typeof BridgeUtils&&(BridgeUtils={});
(function(){function b(a){if(window.WebViewJavascriptBridge)return a(WebViewJavascriptBridge);if(window.WVJBCallbacks)return window.WVJBCallbacks.push(a);window.WVJBCallbacks=[a];var b=document.createElement("iframe");b.style.display="none";b.src="https://__bridge_loaded__";document.documentElement.appendChild(b);setTimeout(function(){document.documentElement.removeChild(b)},0)}BridgeUtils.sendMessage=function(a){b(function(b){b.callHandler("ObjC Echo",a)});console.log(a)};BridgeUtils.bridgeIOSRegister=
function(){b(function(a){a.registerHandler("JS Echo",function(a,b){})})}})();"undefined"==typeof DataImageUtils&&(DataImageUtils={});
(function(){DataImageUtils.setBackground=function(b){if(b){b=b.find(".data-image[data-image]");for(var a=0;a<b.size();a++){var c=$(b.get(a)),d=c.data("image")||"",e="url('"+d+"')";"undefined"!==typeof PageConfig&&PageConfig.cdnDomain&&-1==d.indexOf(PageConfig.cdnDomain)?e="url('"+PageConfig.cdnDomain+d+"')":"undefined"!==typeof FE&&"undefined"!==typeof FE.PageConfig&&FE.PageConfig.cdnDomain&&-1==d.indexOf(FE.PageConfig.cdnDomain)&&(e="url('"+FE.PageConfig.cdnDomain+d+"')");c.css("backgroundImage",
e)}}};DataImageUtils.setSEOTitle=function(b){if(b){b=b.find(".data-title[data-title]");for(var a=0;a<b.size();a++){var c=$(b.get(a));c.attr("title",c.data("title"))}}}})();"undefined"==typeof getDataByAjax&&(getDataByAjax=function(b,a,c){c||(c={});$.ajax({url:b+Math.random(),type:"GET",dataType:"json",data:c}).done(function(c){c.status?200==c.status?a(c):(Trace.error(b),Trace.error(c)):a(c)}).fail(function(a){Trace.error(b);Trace.error(a);DialogHandler.showErrorAlert()})});
"undefined"==typeof DomUtils&&(DomUtils={});(function(){DomUtils.findAncestor=function(b,a){for(;(b=b.parentElement)&&!(b.matches||b.matchesSelector).call(b,a););return b};DomUtils.isImage=function(b){b=b.split(".");switch(b[b.length-1].toLowerCase()){case "jpg":case "jpeg":case "png":return!0}return!1};DomUtils.nameStartsWith=function(b,a){b=document.querySelectorAll(b);const c=[];for(let d=0,e=b.length;d<e;d++)0===b[d].name.indexOf(a)&&c.push(b[d]);return c}})();
"undefined"==typeof UUIDUtils&&(UUIDUtils={});(function(){UUIDUtils.get=function(){return"10000000-1000-4000-8000-100000000000".replace(/[018]/g,b=>(b^crypto.getRandomValues(new Uint8Array(1))[0]&15>>b/4).toString(16))}})();

