$(document).ready(function(){$.extend($.validator.defaults,{invalidHandler:function(a,b){if(a=b.numberOfInvalids())a=$.validator.format($.validator.messages.missHighlightedFields,a),NotifyHandler.errorMsg(a,2E3)},errorPlacement:function(a,b){"file"===b.attr("type")&&"fileinput"===b.data("style")?a.appendTo(b.closest("div.fileinput-holder").parent("div")):a.insertAfter(b)}});$.validator.addMethod("endDate",function(a,b,c){return(b=$(c[0]).val())?0<=DateUtil.compare(b,a):!0});$.validator.addMethod("startDate",
function(a,b,c){return(b=$(c[0]).val())?0<=DateUtil.compare(a,b):!0});$.validator.addMethod("maxNumber",function(a,b,c){b=c[0];if(!b||!a)return!0;a=Number(a.replace(/,/g,""));b=Number(b.replace(/,/g,""));return a<=b},jQuery.validator.messages.maxNumber);$.validator.addMethod("minNumber",function(a,b,c){b=c[0];if(!b||!a)return!0;a=Number(a.replace(/,/g,""));b=Number(b.replace(/,/g,""));return a>=b},jQuery.validator.messages.minNumber);$.validator.addMethod("biggerThanNumber",function(a,b,c){b=c[0];
if(!b||!a)return!0;a=Number(a.replace(/,/g,""));b=Number(b.replace(/,/g,""));return a>b},jQuery.validator.messages.biggerThanNumber);$.validator.addMethod("rangeNumber",function(a,b,c){a=Number(a.replace(/,/g,""));b=Number(c[0].replace(/,/g,""));c=Number(c[1].replace(/,/g,""));return a>=b&&a<=c},jQuery.validator.messages.rangeNumber);$.validator.addMethod("require_from_group",function(a,b,c){const d=this;a=c[1];c=$(a,b.form).filter(function(){return d.elementValue(this)}).length>=c[0];$(b).data("being_validated")||
(b=$(a,b.form),b.data("being_validated",!0),b.valid(),b.data("being_validated",!1));return c});$.validator.addMethod("alphanumeric2",function(a,b,c){return this.optional(b)||/^[0-9a-zA-Z]+$/.test(a)});$.validator.addMethod("alphanumeric2WithSpace",function(a,b,c){return this.optional(b)||/^[0-9a-zA-Z\-_ ]+$/.test(a)});$.validator.addMethod("date2",function(a,b,c){return this.optional(b)||/^(?:19|20)[0-9]{2}\/(?:0[1-9]|1[012])\/(?:0[1-9]|[12][0-9]|3[01])$/.test(a)});$.validator.addMethod("dateTime",
function(a,b,c){return this.optional(b)||/^(?:19|20)[0-9]{2}\/(?:0[1-9]|1[012])\/(?:0[1-9]|[12][0-9]|3[01]) (?:[01][0-9]|2[0-3])(?::[0-5][0-9]){2}$/.test(a)});$.validator.addMethod("cellPhone",function(a,b,c){switch(parseInt(c[0])){case CurrencyType.CNY.value:return this.optional(b)||/^[1]\d{10}$/.test(a);case CurrencyType.SGD.value:return this.optional(b)||/^[89]\d{7}$/.test(a);case CurrencyType.MYR.value:return this.optional(b)||/^0?[1-9]\d{8,9}$/.test(a);case CurrencyType.VND.value:return this.optional(b)||
/^\d{8,10}$/.test(a);case CurrencyType.KRW.value:return this.optional(b)||/^\d{10,11}$/.test(a);case CurrencyType.THB.value:return this.optional(b)||/^\d{9}$/.test(a);case CurrencyType.IDR.value:return this.optional(b)||/^0?[8]\d{7,13}$/.test(a);case CurrencyType.INR.value:return this.optional(b)||/^\d{10}$/.test(a);case CurrencyType.BDT.value:return this.optional(b)||/^\d{10,11}$/.test(a);case CurrencyType.PHP.value:return this.optional(b)||/^[9]\d{9}$/.test(a);case CurrencyType.PKR.value:return this.optional(b)||
/^\d{10}$/.test(a);case CurrencyType.MXN.value:return this.optional(b)||/^\d{10}$/.test(a);case CurrencyType.USD.value:return this.optional(b)||/^\d{8,9}$/.test(a);case CurrencyType.BRL.value:return this.optional(b)||/^\d{10,11}$/.test(a);case CurrencyType.NGN.value:return this.optional(b)||/^\d{10}$/.test(a);case CurrencyType.ZAR.value:return this.optional(b)||/^\d{9}$/.test(a);case CurrencyType.GHS.value:return this.optional(b)||/^\d{9}$/.test(a);default:return!1}});$.validator.addMethod("byCallingCode",
function(a,b,c){switch(parseInt(c[0])){case CallingCodeType.China.value:return this.optional(b)||/^[1]\d{10}$/.test(a);case CallingCodeType.Singapore.value:return this.optional(b)||/^[89]\d{7}$/.test(a);case CallingCodeType.Malaysia.value:return this.optional(b)||/^0?[1-9]\d{8,9}$/.test(a);case CallingCodeType.Vietnam.value:return this.optional(b)||/^\d{8,10}$/.test(a);case CallingCodeType.SouthKorea.value:return this.optional(b)||/^\d{10,11}$/.test(a);case CallingCodeType.Thailand.value:return this.optional(b)||
/^\d{9}$/.test(a);case CallingCodeType.Indonesia.value:return this.optional(b)||/^0?[8]\d{7,13}$/.test(a);case CallingCodeType.India.value:return this.optional(b)||/^\d{10}$/.test(a);case CallingCodeType.Bangladesh.value:return this.optional(b)||/^\d{10,11}$/.test(a);case CallingCodeType.Philippines.value:return this.optional(b)||/^[9]\d{9}$/.test(a);case CallingCodeType.Pakistan.value:return this.optional(b)||/^\d{10}$/.test(a);case CallingCodeType.Mexico.value:return this.optional(b)||/^\d{10}$/.test(a);
case CallingCodeType.US.value:return this.optional(b)||/^\d{10}$/.test(a);case CallingCodeType.Cambodia.value:return this.optional(b)||/^\d{8,9}$/.test(a);case CallingCodeType.Brazil.value:return this.optional(b)||/^\d{10,11}$/.test(a);case CallingCodeType.Nigeria.value:return this.optional(b)||/^\d{10}$/.test(a);case CallingCodeType.ZA.value:return this.optional(b)||/^\d{9}$/.test(a);case CallingCodeType.GH.value:return this.optional(b)||/^\d{9}$/.test(a);default:return this.optional(b)||/^\d{8,11}$/.test(a)}});
$.validator.addMethod("custom",function(a,b,c){return this.optional(b)||c});$.validator.addMethod("qqId",function(a,b,c){return this.optional(b)||/^\d{5,11}$/.test(a)});$.validator.addMethod("weChatId",function(a,b,c){return this.optional(b)||/^[a-zA-Z]{1}[a-zA-Z0-9_-]{6,20}$/.test(a)});$.validator.addMethod("skypeId",function(a,b,c){return this.optional(b)||/^[a-zA-Z]{1}[a-zA-Z0-9\.,_-]{6,32}$/.test(a)});$.validator.addMethod("telegramId",function(a,b,c){return this.optional(b)||/^[a-zA-Z]{1}[a-zA-Z0-9]{5,32}$/.test(a)});
$.validator.addMethod("lineId",function(a,b,c){return this.optional(b)||/^[a-zA-Z0-9\._-]{4,48}$/.test(a)});$.validator.addMethod("moneyAmount",function(a,b,c){c=$(b).attr("data-scale");return null!=c&&"0"==c?this.optional(b)||/^\d{1,20}$/.test(a):this.optional(b)||/^\d{1,20}(\.\d{1,2})?$/.test(a)});$.validator.addMethod("decimal",function(a,b,c){const d=$(b).attr("data-scale");return null!=d&&"0"==d?this.optional(b)||/^-?\d{1,20}$/.test(a):this.optional(b)||(new RegExp("^-?\\d{1,20}(\\.\\d{1,"+c+
"})?$")).test(a)});$.validator.addMethod("number",function(a,b,c){c=$(b).attr("data-scale");return null!=c&&"0"==c?this.optional(b)||/^-?\d{1,20}$/.test(a):this.optional(b)||/^-?\d{1,20}(\.\d{1,2})?$/.test(a)});$.validator.addMethod("cnBankAccNumber",function(a,b,c){return this.optional(b)||/^\d{1,19}$/.test(a)});$.validator.addMethod("userId",function(a,b,c){return this.optional(b)||/^[0-9a-z]{4,15}$/.test(a)},jQuery.validator.messages.invalidUserIdFormat);$.validator.addMethod("userName",function(a,
b,c){return this.optional(b)||/^[a-zA-Z. -]{1,13}$/.test(a)});$.validator.addMethod("managerId",function(a,b,c){return this.optional(b)||/^[0-9a-z]{6,12}$/.test(a)},jQuery.validator.messages.invalidFormat);$.validator.addMethod("affiliateUserId",function(a,b,c){return this.optional(b)||/^[0-9a-z]{6,18}$/.test(a)},jQuery.validator.messages.invalidFormat);$.validator.addMethod("password2",function(a,b,c){c=/^[0-9a-zA-Z]{6,20}$/;let d=/^[0-9]{6,20}$/,e=/^[a-zA-Z]{6,20}$/;return this.optional(b)||c.test(a)&&
!d.test(a)&&!e.test(a)});$.validator.addMethod("playerLoginPassword",function(a,b,c){c=/^(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d@$!%*#]{6,20}$/;return this.optional(b)||c.test(a)});$.validator.addMethod("playerRegisterPassword",function(a,b,c){c=/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d@$!%*#]{6,20}$/;return this.optional(b)||c.test(a)});$.validator.addMethod("playerPasswordEqualToAccount",function(a,b,c){c=$(c);return this.optional(b)||a.toUpperCase()!==c.val().toUpperCase()});$.validator.addMethod("password918kiss",
function(a,b,c){c=/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,15}$/;return this.optional(b)||c.test(a)},jQuery.validator.messages.password918Kiss);$.validator.addMethod("pattern",function(a,b,c){if(this.optional(b))return!0;"string"===typeof c&&(c=new RegExp("^(?:"+c+")$"));return c.test(a)},jQuery.validator.messages.invalidFormat);$.validator.addMethod("DBNumber",function(a,b,c){return this.optional(b)||(new RegExp("^-?\\d{0,"+(c[0]-c[1])+"}(\\.\\d{0,"+c[1]+"})?$")).test(a)},jQuery.validator.messages.number);
$.validator.addMethod("minStrict",function(a,b,c){return this.optional(b)||a>c});$.validator.addMethod("notEqual",function(a,b,c){return this.optional(b)||0!=a});$.validator.addMethod("noUrlCharacter",function(a,b,c){return this.optional(b)||!/[#%&=/.?:]/.test(a)});$.validator.addMethod("checkAgeOver18",function(a,b,c){a=new Date(b.value);c=new Date;const d=c.getMonth()+1;c=new Date(c.getFullYear()-18+"/"+d+"/"+c.getDate());return this.optional(b)||a<=c});$.validator.addMethod("checkAgeOver21",function(a,
b,c){a=new Date(b.value);c=new Date;const d=c.getMonth()+1;c=new Date(c.getFullYear()-21+"/"+d+"/"+c.getDate());return this.optional(b)||a<=c});$.validator.addMethod("maxByteLength",function(a,b,c){return this.optional(b)?!0:encodeURIComponent(a).replace(/%[A-F\d]{2}/g,"U").length<=c},jQuery.validator.messages.maxByteLength);$.validator.addMethod("tagsinput",function(a,b,c){const d=c[2],e=c[1]-d,g=c[3],h=[];let f=!0;$("#"+b.id+"_tagsinput span span").each(function(a,b){a=$(b).text().trim();if((new RegExp("^-?\\d{0,"+
e+"}(\\.\\d{0,"+d+"})?$")).test(a)&&a>g)h.push(a);else return f=!1});return f});$.validator.addMethod("gender",function(a,b,c){return 0<=parseInt(a)});$.validator.addMethod("marital",function(a,b,c){return 0<=parseInt(a)});$.validator.addMethod("exactLength",function(a,b,c){return this.optional(b)||a.length===c},jQuery.validator.messages.exactLength);$.validator.addMethod("maxDigitalLength",function(a,b,c){a=a.replace(/,/g,"");a.match(/\./)&&(a=a.replace(/\.?0*$/,""));return this.optional(b)||a.length<=
c},jQuery.validator.messages.maxDigitslength);$.validator.addMethod("creditNumber",function(a,b,c){return this.optional(b)||/^\d{15,16}$/.test(a)});$.validator.addMethod("cvvNumber",function(a,b,c){return this.optional(b)||/^\d{3,4}$/.test(a)});$.validator.addMethod("expDate",function(a,b,c){return this.optional(b)||/^\d{4}$/.test(a)});$.validator.addMethod("referenceNo",function(a,b,c){if(c[2]!==CurrencyType.INR.unique())return!0;b=CompanyBankPaymentType.getInstanceOf(c[0]);if(null===b)return!0;
if(b===CompanyBankPaymentType.PHONEPE||b===CompanyBankPaymentType.GPAY||b===CompanyBankPaymentType.PAYTM||b===CompanyBankPaymentType.UPI){if(b===CompanyBankPaymentType.PHONEPE||b===CompanyBankPaymentType.GPAY||b===CompanyBankPaymentType.UPI)return/^\d{12}$/.test(a);if(b===CompanyBankPaymentType.PAYTM)return c=/^\d{18,19}$/,/^\d{12}$/.test(a)||c.test(a)}if(b===CompanyBankPaymentType.REAL_BANK){c=BankTransferType.getInstanceOf(c[1]);if(c===BankTransferType.IMPS||c===BankTransferType.INTERNAL_ICCI)return/^\d{12}$/.test(a);
if(c===BankTransferType.RTGS)return/^[0-9A-Z]{22}$/.test(a);if(c===BankTransferType.NEFT)return/^[0-9A-Z]{16}$/.test(a);if(c===BankTransferType.INTERNAL_SBIN)return/^[0-9A-Z]{10}$/.test(a)}return!0},jQuery.validator.messages.referenceNo)});"undefined"==typeof ValidatorUtil&&(ValidatorUtil={});
(function(){ValidatorUtil.applyMultiInputNamingRules=function(a,b,c){a.prop("alt")||(a.attr("alt",a.attr("name")),a.attr("name",a.attr("name")+"-"+b),a.rules("add",c))};ValidatorUtil.removeMultiInputNamingRules=function(a){a.attr("name",a.attr("alt"));a.removeAttr("alt")}})();

